In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score,recall_score,f1_score
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
def evaluation_classif_L(conf_mat):
    TP = conf_mat[0,0]
    FP = conf_mat[1,0]+conf_mat[2,0]+conf_mat[3,0]+conf_mat[4,0]
    FN = conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]
    TN = conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_N(conf_mat):
    TP = conf_mat[1,1]
    FP = conf_mat[0,1]+conf_mat[2,1]+conf_mat[3,1]+conf_mat[4,1]
    FN = conf_mat[1,0]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]
    TN = conf_mat[0,0]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[2,0]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,0]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_R(conf_mat):
    TP = conf_mat[2,2]
    FP = conf_mat[0,2]+conf_mat[1,2]+conf_mat[3,2]+conf_mat[4,2]
    FN = conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,3]+conf_mat[2,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_S(conf_mat):
    TP = conf_mat[3,3]
    FP = conf_mat[0,3]+conf_mat[1,3]+conf_mat[2,3]+conf_mat[4,3]
    FN = conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,4]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,4]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_T(conf_mat):
    TP = conf_mat[4,4]
    FP = conf_mat[0,4]+conf_mat[1,4]+conf_mat[2,4]+conf_mat[3,4]
    FN = conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
dataset_obuka_poc = pd.read_csv('drive/My Drive/diplomski2021/svi_preimenovani.csv')
#dataset_test = pd.read_csv('cookies_test.csv', header=0)
print(dataset_obuka_poc.shape)

dataset_obuka_poc.tail()

Mounted at /content/drive
(9015, 386)


name  pcm_RMSenergy_sma_max  ...  F0_sma_de_kurtosis  class
0  '1BMZD01L__1100.wav'               0.126734  ...            5.684139      ?
1  '1BMZD02L__1100.wav'               0.104423  ...            6.739047      ?
2  '1BMZD03L__1100.wav'               0.115782  ...            5.404254      ?
3  '1BMZD04L__1100.wav'               0.109434  ...            5.881023      ?
4  '1BMZD05L__1100.wav'               0.113291  ...            6.588470      ?

[5 rows x 386 columns]

In [ ]:
dataset_obuka_poc.loc[0:1752, 'class'] = 'L'
dataset_obuka_poc.loc[1753:3588, 'class'] = 'N'
dataset_obuka_poc.loc[3589:5341, 'class'] = 'R'
dataset_obuka_poc.loc[5342:7177, 'class'] = 'T'
dataset_obuka_poc.loc[7178:9016, 'class'] = 'S'

In [ ]:
lista_izbaci = ['1052', '1101','1102','1103','1104','1105','1100']
indeksi_izbaci = []
for i in range(0, len(lista_izbaci)):    
    indeksi1 = dataset_obuka_poc.loc[dataset_obuka_poc['name'].str.find(lista_izbaci[i]) !=-1].index
    dataset_obuka_poc.drop(indeksi1, axis = 0, inplace = True)
dataset_obuka = dataset_obuka_poc
print(dataset_obuka.head())
print(dataset_obuka.shape)

                          name  ...  class
348  '1_0_0_MMMD01L__0001.wav'  ...      L
349  '1_0_0_MMMD01L__0002.wav'  ...      L
350  '1_0_0_MMMD01L__0003.wav'  ...      L
351  '1_0_0_MMMD01L__0005.wav'  ...      L
352  '1_0_0_MMMD01L__1003.wav'  ...      L

[5 rows x 386 columns]
(6937, 386)


In [ ]:
X_obuka= dataset_obuka.iloc[:, :-1]
y_obuka = dataset_obuka.iloc[:, -1]

In [ ]:
dataset_obuka.drop(['pcm_RMSenergy_sma_minPos','pcm_zcr_sma_maxPos','voiceProb_sma_minPos', 'F0_sma_min','F0_sma_minPos'],axis = 1,inplace = True)
print(dataset_obuka.shape)

(6937, 381)


In [ ]:
bez_imena = dataset_obuka.drop(['name'], axis = 1)

In [ ]:
X_obuka= bez_imena.iloc[:, :-1]
y_obuka = bez_imena.iloc[:, -1]

In [ ]:
from sklearn.model_selection import GridSearchCV
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
parameters = {'criterion':('gini', 'entropy'), 'max_depth':[5, 10, 15,20], 'class_weight':(None, 'balanced')}
dt = DecisionTreeClassifier()
clf=GridSearchCV(dt, parameters,cv=kf)
clf.fit(X_std, y_obuka)
print(clf.best_score_)
print(clf.best_params_)

NameError: ignored

In [ ]:
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
     for m in [5,10,15,20,35]:
         for w in [None,'balanced']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 classifier.fit(X_std1, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_std_test)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre c=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre c= entropy  i m= 35 weigth je: balanced  tacnost je:  0.6067475911856316  a mat. konf. je:
# [[ 751.  128.  221.  212.   34.]
#  [ 145.  809.  135.  201.  126.]
#  [ 225.  126.  784.  175.   36.]
#  [ 177.  196.  180.  764.   98.]
#  [  37.  124.   39.  113. 1101.]]

za parametre c= gini  i m= 5 weigth je: None  tacnost je:  0.5072844542585176  a mat. konf. je:
[[659. 150. 182. 311.  44.]
 [190. 519. 136. 450. 121.]
 [248. 181. 601. 274.  42.]
 [202. 155. 152. 804. 102.]
 [ 39. 135.  27. 277. 936.]]
za parametre c= gini  i m= 5 weigth je: balanced  tacnost je:  0.5039711649221735  a mat. konf. je:
[[740. 121. 185. 247.  53.]
 [248. 483. 141. 415. 129.]
 [312. 156. 600. 238.  40.]
 [291. 138. 153. 709. 124.]
 [ 54. 125.  30. 241. 964.]]
za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5867131587592682  a mat. konf. je:
[[ 712.  130.  224.  251.   29.]
 [ 118.  795.  155.  218.  130.]
 [ 208.  167.  710.  239.   22.]
 [ 165.  190.  159.  812.   89.]
 [  33.  155.   36.  149. 1041.]]
za parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5815241754723022  a mat. konf. je:
[[ 719.  126.  218.  264.   19.]
 [ 142.  787.  141.  221.  125.]
 [ 217.  137.  714.  246.   32.]
 [ 210.  161.  159.  797.   88.]
 [  35.  159.   40.  163. 

In [ ]:
lista = ['0001','0002','0003','0005','1003','1004','1005','1007','1008','1009','1011','1012','1014','1015','1016','1023','1027','1036','1045','1051','1053','1057','1060']
indeksi_svi = []
for i in range(0,len(lista)):
    indeksi = dataset_obuka[dataset_obuka['name'].str.find(lista[i]) !=-1].index
    indeksi_svi.append(indeksi)
#print(indeksi_svi)

#dataset_obuka.drop(['name'],axis = 1, inplace = True)
for i in range(0,len(lista)): 
  bez_imena = dataset_obuka.drop(['name'], axis = 1)
  vars()["g"+lista[i]]= bez_imena.loc[indeksi_svi[i]]

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  X_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  X_test1_std = s.transform(X_test1)

  classifier_kon = DecisionTreeClassifier(class_weight='balanced',criterion='entropy',max_depth=10)  
  classifier_kon.fit(X_obuka29_std, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test1_std) 
  #navedi tacne nazive umesto y_test1
  conf_mat_dt1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  fin_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(fin_conf_mat)

# [[457. 212. 353. 247.  77.]
#  [291. 373. 186. 335. 231.]
#  [257. 173. 549. 277.  90.]
#  [285. 234. 228. 499. 169.]
#  [ 66. 327.  85. 239. 697.]]

[[25.  0. 31.  1.  0.]
 [14.  6. 26. 12.  2.]
 [ 4.  0. 53.  0.  0.]
 [ 4.  7. 14. 32.  3.]
 [ 4. 10.  4. 30. 12.]]
[[37. 20. 49.  6.  2.]
 [23. 18. 37. 32. 10.]
 [ 9. 14. 82.  9.  0.]
 [ 6. 32. 30. 45.  7.]
 [10. 23.  7. 54. 26.]]
[[ 43.  26.  91.   9.   2.]
 [ 26.  46.  45.  40.  23.]
 [ 15.  19. 124.  13.   0.]
 [ 11.  47.  46.  55.  21.]
 [ 10.  33.   8.  56.  73.]]
[[ 73.  27. 107.  19.   2.]
 [ 68.  47.  55.  47.  23.]
 [ 36.  19. 153.  20.   0.]
 [ 46.  47.  51.  75.  21.]
 [ 10.  56.   9.  60. 105.]]
[[105.  39. 114.  24.   3.]
 [ 97.  58.  65.  54.  26.]
 [ 59.  34. 162.  29.   1.]
 [ 78.  62.  55.  84.  21.]
 [ 13.  68.   9.  61. 149.]]
[[117.  53. 119.  50.   5.]
 [115.  75.  68.  75.  29.]
 [ 72.  37. 175.  56.   4.]
 [ 81.  79.  56. 122.  24.]
 [ 14. 110.   9.  75. 154.]]
[[140.  58. 127.  73.   5.]
 [120. 100.  68. 105.  31.]
 [ 75.  41. 191.  89.   7.]
 [ 84.  85.  59. 172.  24.]
 [ 20. 136.  18.  83. 167.]]
[[166.  62. 147.  82.   5.]
 [124. 105.  70. 147.  40.]
 [ 91. 

In [ ]:
L = evaluation_classif_L(fin_conf_mat)
N = evaluation_classif_N(fin_conf_mat)
R = evaluation_classif_R(fin_conf_mat)
S = evaluation_classif_S(fin_conf_mat)
T = evaluation_classif_T(fin_conf_mat)

print(fin_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST DT JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost DT JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost DT JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost DT JE ', prosecna_osetljivost)

# PROSECNA TACNOST DT JE  0.748479169669886
# PROSECNA specificnost DT JE  0.8427939466457977
# PROSECNA preciznost DT JE  0.3751117022342615
# PROSECNA osetljivost DT JE  0.37127916456253257

[[457. 212. 353. 247.  77.]
 [291. 373. 186. 335. 231.]
 [257. 173. 549. 277.  90.]
 [285. 234. 228. 499. 169.]
 [ 66. 327.  85. 239. 697.]]
PROSECNA TACNOST DT JE  0.748479169669886
PROSECNA specificnost DT JE  0.8427939466457977
PROSECNA preciznost DT JE  0.3751117022342615
PROSECNA osetljivost DT JE  0.37127916456253257


In [ ]:
#PCA -TRAZENJE OPTIMALNIH PARAMETARA ZA n=125
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
     for m in [5,10,15,20,35]:
         for w in [None,'balanced']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 pca = PCA(n_components=125)
                 pca.fit(X_std1)
                 X_train_r = pca.transform(X_std1)
                 X_test_r=pca.transform(X_std_test)
                 classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                 classifier.fit(X_train_r, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_test_r)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre c=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za n=125 parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.533517763056668  a mat. konf. je:
# [[676. 151. 236. 236.  47.]
#  [186. 660. 168. 254. 148.]
#  [224. 164. 730. 188.  40.]
#  [203. 200. 220. 656. 136.]
#  [ 66. 159.  44. 166. 979.]]

za parametre c= gini  i m= 5 weigth je: None  tacnost je:  0.4595695530854032  a mat. konf. je:
[[541. 254. 333. 178.  40.]
 [191. 595. 195. 279. 156.]
 [282. 236. 678. 123.  27.]
 [214. 332. 271. 465. 133.]
 [ 44. 222.  51. 188. 909.]]
za parametre c= gini  i m= 5 weigth je: balanced  tacnost je:  0.45740650639786085  a mat. konf. je:
[[545. 221. 368. 174.  38.]
 [221. 565. 223. 260. 147.]
 [266. 223. 724. 109.  24.]
 [234. 320. 294. 439. 128.]
 [ 50. 220.  62. 182. 900.]]
za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5267450129121599  a mat. konf. je:
[[664. 173. 227. 223.  59.]
 [199. 694. 149. 233. 141.]
 [266. 193. 684. 172.  31.]
 [231. 211. 203. 654. 116.]
 [ 63. 179.  40. 174. 958.]]
za parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.533517763056668  a mat. konf. je:
[[676. 151. 236. 236.  47.]
 [186. 660. 168. 254. 148.]
 [224. 164. 730. 188.  40.]
 [203. 200. 220. 656. 136.]
 [ 66. 159.  44. 166. 979.]]
za parametre c= gini  i m= 15 weigth je: N

In [ ]:
#PCA -TRAZENJE OPTIMALNIH PARAMETARA ZA n=150
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
     for m in [5,10,15,20,35]:
         for w in [None,'balanced']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 pca = PCA(n_components=150)
                 pca.fit(X_std1)
                 X_train_r = pca.transform(X_std1)
                 X_test_r=pca.transform(X_std_test)
                 classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                 classifier.fit(X_train_r, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_test_r)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre c=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za N = 150 parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5251560479226186  a mat. konf. je:
# [[666. 142. 244. 251.  43.]
#  [194. 654. 171. 256. 141.]
#  [256. 167. 710. 178.  35.]
#  [227. 196. 217. 648. 127.]
#  [ 58. 163.  53. 175. 965.]]

za parametre c= gini  i m= 5 weigth je: None  tacnost je:  0.4579845386761813  a mat. konf. je:
[[535. 254. 335. 182.  40.]
 [190. 594. 196. 280. 156.]
 [280. 236. 678. 124.  28.]
 [217. 332. 273. 461. 132.]
 [ 45. 222.  51. 187. 909.]]
za parametre c= gini  i m= 5 weigth je: balanced  tacnost je:  0.45668604530275997  a mat. konf. je:
[[540. 222. 371. 174.  39.]
 [216. 569. 224. 260. 147.]
 [266. 223. 725. 108.  24.]
 [233. 323. 297. 434. 128.]
 [ 49. 221.  62. 182. 900.]]
za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5214106898544938  a mat. konf. je:
[[655. 159. 247. 240.  45.]
 [188. 686. 164. 239. 139.]
 [258. 181. 691. 182.  34.]
 [227. 203. 219. 644. 122.]
 [ 54. 197.  48. 174. 941.]]
za parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5251560479226186  a mat. konf. je:
[[666. 142. 244. 251.  43.]
 [194. 654. 171. 256. 141.]
 [256. 167. 710. 178.  35.]
 [227. 196. 217. 648. 127.]
 [ 58. 163.  53. 175. 965.]]
za parametre c= gini  i m= 15 weigth je: 

In [ ]:
#PCA -TRAZENJE OPTIMALNIH PARAMETARA ZA n=175
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
     for m in [5,10,15,20,35]:
         for w in [None,'balanced']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 pca = PCA(n_components=175)
                 pca.fit(X_std1)
                 X_train_r = pca.transform(X_std1)
                 X_test_r=pca.transform(X_std_test)
                 classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                 classifier.fit(X_train_r, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_test_r)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre c=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5211214657900537  a mat. konf. je:
# [[656. 140. 247. 259.  44.]
#  [185. 679. 168. 258. 126.]
#  [255. 193. 688. 175.  35.]
#  [209. 222. 211. 653. 120.]
#  [ 63. 180.  46. 186. 939.]]

za parametre c= gini  i m= 5 weigth je: None  tacnost je:  0.4587047918460022  a mat. konf. je:
[[541. 254. 334. 177.  40.]
 [192. 593. 195. 279. 157.]
 [282. 236. 678. 123.  27.]
 [214. 332. 273. 463. 133.]
 [ 44. 222.  51. 190. 907.]]
za parametre c= gini  i m= 5 weigth je: balanced  tacnost je:  0.45639786086471973  a mat. konf. je:
[[544. 221. 368. 174.  39.]
 [221. 565. 223. 260. 147.]
 [267. 223. 724. 108.  24.]
 [237. 320. 294. 436. 128.]
 [ 50. 222.  62. 183. 897.]]
za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5211214657900537  a mat. konf. je:
[[656. 140. 247. 259.  44.]
 [185. 679. 168. 258. 126.]
 [255. 193. 688. 175.  35.]
 [209. 222. 211. 653. 120.]
 [ 63. 180.  46. 186. 939.]]
za parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5166537752993084  a mat. konf. je:
[[642. 130. 263. 261.  50.]
 [207. 663. 154. 248. 144.]
 [238. 156. 714. 199.  39.]
 [225. 202. 226. 621. 141.]
 [ 63. 171.  56. 180. 944.]]
za parametre c= gini  i m= 15 weigth je: 

In [ ]:
#PCA -TRAZENJE OPTIMALNIH PARAMETARA ZA n=200
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
     for m in [5,10,15,20,35]:
         for w in [None,'balanced']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 pca = PCA(n_components=200)
                 pca.fit(X_std1)
                 X_train_r = pca.transform(X_std1)
                 X_test_r=pca.transform(X_std_test)
                 classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                 classifier.fit(X_train_r, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_test_r)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre c=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za n=200 parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5225609325032956  a mat. konf. je:
# [[662. 143. 239. 252.  50.]
#  [204. 646. 159. 253. 154.]
#  [232. 174. 718. 181.  41.]
#  [211. 200. 225. 651. 128.]
#  [ 53. 172.  49. 192. 948.]]

za parametre c= gini  i m= 5 weigth je: None  tacnost je:  0.45928116072208286  a mat. konf. je:
[[540. 264. 333. 169.  40.]
 [188. 605. 195. 274. 154.]
 [282. 241. 678. 118.  27.]
 [215. 340. 270. 458. 132.]
 [ 42. 233.  51. 183. 905.]]
za parametre c= gini  i m= 5 weigth je: balanced  tacnost je:  0.45567677599377887  a mat. konf. je:
[[539. 226. 368. 174.  39.]
 [219. 567. 223. 261. 146.]
 [267. 223. 724. 108.  24.]
 [237. 320. 294. 439. 125.]
 [ 50. 221.  62. 189. 892.]]
za parametre c= gini  i m= 10 weigth je: None  tacnost je:  0.5209763339446336  a mat. konf. je:
[[638. 153. 249. 258.  48.]
 [191. 685. 149. 252. 139.]
 [252. 185. 696. 178.  35.]
 [228. 194. 205. 658. 130.]
 [ 58. 200.  41. 178. 937.]]
za parametre c= gini  i m= 10 weigth je: balanced  tacnost je:  0.5225609325032956  a mat. konf. je:
[[662. 143. 239. 252.  50.]
 [204. 646. 159. 253. 154.]
 [232. 174. 718. 181.  41.]
 [211. 200. 225. 651. 128.]
 [ 53. 172.  49. 192. 948.]]
za parametre c= gini  i m= 15 weigth je:

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
pca_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XPCA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XPCA_test1_std = s.transform(X_test1)

  pca = PCA(n_components=125)
  pca.fit(XPCA_obuka29_std)
  X_train_PCA = pca.transform(XPCA_obuka29_std)
  X_test_PCA=pca.transform(XPCA_test1_std)

  classifier_kon = DecisionTreeClassifier(class_weight='balanced',criterion='gini',max_depth=10)  
  classifier_kon.fit(X_train_PCA, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_PCA) 
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  pca_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(pca_conf_mat)

#   [[486. 244. 247. 289.  80.]
#  [337. 281. 220. 330. 248.]
#  [330. 199. 482. 267.  68.]
#  [291. 301. 204. 438. 181.]
#  [ 98. 276.  57. 180. 803.]]

[[31.  6. 15.  5.  0.]
 [ 9. 13. 28. 10.  0.]
 [ 8. 10. 33.  6.  0.]
 [16.  3. 17. 24.  0.]
 [37.  5. 11.  5.  2.]]
[[56. 22. 20. 15.  1.]
 [28. 19. 37. 33.  3.]
 [24. 21. 52. 14.  3.]
 [25. 30. 18. 47.  0.]
 [38. 48. 11.  9. 14.]]
[[72. 29. 41. 27.  2.]
 [38. 26. 45. 58. 13.]
 [33. 26. 74. 35.  3.]
 [32. 47. 33. 65.  3.]
 [38. 55. 11. 14. 62.]]
[[ 85.  33.  67.  41.   2.]
 [ 45.  37.  61.  78.  19.]
 [ 53.  28.  96.  48.   3.]
 [ 60.  49.  43.  85.   3.]
 [ 38.  62.  12.  19. 109.]]
[[115.  38.  74.  50.   8.]
 [ 71.  42.  76.  81.  30.]
 [ 83.  30. 107.  57.   8.]
 [ 77.  63.  49. 100.  11.]
 [ 40.  67.  12.  19. 162.]]
[[138.  47.  81.  61.  17.]
 [ 91.  54.  87.  85.  45.]
 [102.  35. 126.  67.  14.]
 [ 79.  78.  58. 114.  33.]
 [ 40.  82.  17.  24. 199.]]
[[152.  77.  85.  70.  19.]
 [ 94.  70.  91.  96.  73.]
 [128.  37. 141.  82.  15.]
 [ 83.  93.  69. 134.  45.]
 [ 42.  97.  17.  32. 236.]]
[[177.  79. 101.  86.  19.]
 [103.  87.  95. 125.  76.]
 [140.  37. 185.  85.  15.]
 [10

In [ ]:
L = evaluation_classif_L(pca_conf_mat)
N = evaluation_classif_N(pca_conf_mat)
R = evaluation_classif_R(pca_conf_mat)
S = evaluation_classif_S(pca_conf_mat)
T = evaluation_classif_T(pca_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost JE ', prosecna_osetljivost)

# PROSECNA TACNOST JE  0.7435779155254434
# PROSECNA specificnost JE  0.8397296825716131
# PROSECNA preciznost JE  0.36052347374169713
# PROSECNA osetljivost JE  0.35900947443310083

PROSECNA TACNOST JE  0.7435779155254434
PROSECNA specificnost JE  0.8397296825716131
PROSECNA preciznost JE  0.36052347374169713
PROSECNA osetljivost JE  0.35900947443310083


In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=4
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
    for m in [5,10,15,20,35]:
        for w in [None,'balanced']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=4)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 4, k=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 4, k= gini  i m= 10 weigth je: None  tacnost je:  0.6769585521746906  a mat. konf. je:
# [[ 868.  121.  182.  145.   30.]
#  [  97.  983.   97.  118.  121.]
#  [ 149.  123.  893.  157.   24.]
#  [ 145.  149.  137.  860.  124.]
#  [  31.  154.   16.  121. 1092.]]

za parametre  n_components= 4, k= gini  i m= 5 weigth je: None  tacnost je:  0.6752290296958885  a mat. konf. je:
[[ 852.  142.  181.  157.   14.]
 [ 117.  991.  102.  103.  103.]
 [ 137.  152.  885.  163.    9.]
 [ 145.  148.  169.  854.   99.]
 [  52.  123.   39.   98. 1102.]]
za parametre  n_components= 4, k= gini  i m= 5 weigth je: balanced  tacnost je:  0.6722024693206249  a mat. konf. je:
[[ 871.  116.  208.  139.   12.]
 [ 117.  934.  128.  134.  103.]
 [ 125.  133.  907.  175.    6.]
 [ 147.  122.  193.  860.   93.]
 [  45.  109.   54.  115. 1091.]]
za parametre  n_components= 4, k= gini  i m= 10 weigth je: None  tacnost je:  0.6769585521746906  a mat. konf. je:
[[ 868.  121.  182.  145.   30.]
 [  97.  983.   97.  118.  121.]
 [ 149.  123.  893.  157.   24.]
 [ 145.  149.  137.  860.  124.]
 [  31.  154.   16.  121. 1092.]]
za parametre  n_components= 4, k= gini  i m= 10 weigth je: balanced  tacnost je:  0.6768080142719912  a mat. konf. je:
[[ 880.  109.  189.  124.   44.]
 [ 

In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=3
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for c in ['gini', 'entropy']:
    for m in [5,10,15,20,35]:
        for w in [None,'balanced']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=3)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = DecisionTreeClassifier(class_weight=w,criterion=c,max_depth=m)  
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 3, k=', c, ' i m=', m, 'weigth je:',w,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 3, k= gini  i m= 5 weigth je: None  tacnost je:  0.6714768100935248  a mat. konf. je:
# [[8.750e+02 1.350e+02 1.540e+02 1.710e+02 1.100e+01]
#  [1.110e+02 1.007e+03 8.200e+01 1.120e+02 1.040e+02]
#  [1.240e+02 1.750e+02 7.820e+02 2.610e+02 4.000e+00]
#  [1.520e+02 1.430e+02 1.270e+02 8.990e+02 9.400e+01]
#  [3.400e+01 1.460e+02 1.000e+00 1.380e+02 1.095e+03]]

za parametre  n_components= 3, k= gini  i m= 5 weigth je: None  tacnost je:  0.6714768100935248  a mat. konf. je:
[[8.750e+02 1.350e+02 1.540e+02 1.710e+02 1.100e+01]
 [1.110e+02 1.007e+03 8.200e+01 1.120e+02 1.040e+02]
 [1.240e+02 1.750e+02 7.820e+02 2.610e+02 4.000e+00]
 [1.520e+02 1.430e+02 1.270e+02 8.990e+02 9.400e+01]
 [3.400e+01 1.460e+02 1.000e+00 1.380e+02 1.095e+03]]
za parametre  n_components= 3, k= gini  i m= 5 weigth je: balanced  tacnost je:  0.6674411883345601  a mat. konf. je:
[[8.670e+02 1.230e+02 1.560e+02 1.890e+02 1.100e+01]
 [1.250e+02 9.490e+02 9.500e+01 1.400e+02 1.070e+02]
 [1.150e+02 1.510e+02 7.880e+02 2.880e+02 4.000e+00]
 [1.540e+02 1.130e+02 1.250e+02 9.290e+02 9.400e+01]
 [4.200e+01 1.290e+02 1.000e+00 1.450e+02 1.097e+03]]
za parametre  n_components= 3, k= gini  i m= 10 weigth je: None  tacnost je:  0.6530261445247036  a mat. konf. je:
[[ 855.  134.  171.  161.   25.]
 [ 107.  940.  127.  110.  132.]
 [ 162.  133.  831.  209.   11.]
 [ 165.  135.  161.  8

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
LDA_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XLDA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XLDA_test1_std = s.transform(X_test1)

  lda = LinearDiscriminantAnalysis(n_components=4)
  lda.fit(XLDA_obuka29_std, y_obuka29)
  X_train_29_lda = lda.transform(XLDA_obuka29_std)
  X_test_29_lda = lda.transform(XLDA_test1_std)

  classifier_kon = DecisionTreeClassifier(class_weight=None,criterion='gini',max_depth=10)
  classifier_kon.fit(X_train_29_lda, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_29_lda) 
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  LDA_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(LDA_conf_mat)

#   [[580. 203. 224. 237. 102.]
#  [223. 504. 215. 216. 258.]
#  [275. 194. 621. 186.  70.]
#  [243. 240. 232. 468. 232.]
#  [ 54. 215.  74. 148. 923.]]

[[21.  4. 30.  2.  0.]
 [ 2.  5. 51.  2.  0.]
 [10.  0. 47.  0.  0.]
 [10.  0. 38. 12.  0.]
 [ 4. 10. 41.  5.  0.]]
[[33. 38. 33.  2.  8.]
 [ 5. 52. 54.  4.  5.]
 [12. 44. 52.  3.  3.]
 [12. 24. 38. 25. 21.]
 [ 4. 17. 41. 14. 44.]]
[[40. 42. 70. 11.  8.]
 [ 9. 96. 57. 13.  5.]
 [24. 55. 81.  8.  3.]
 [16. 41. 67. 34. 22.]
 [ 6. 26. 41. 24. 83.]]
[[ 42.  51.  73.  54.   8.]
 [ 11. 100.  66.  58.   5.]
 [ 36.  55. 108.  26.   3.]
 [ 27.  41.  77.  73.  22.]
 [  6.  31.  41.  25. 137.]]
[[ 98.  51.  74.  54.   8.]
 [ 31. 131.  70.  59.   9.]
 [ 77.  58. 120.  27.   3.]
 [ 48.  48.  89.  84.  31.]
 [  6.  31.  41.  25. 197.]]
[[126.  65.  80.  59.  14.]
 [ 33. 159.  82.  60.  28.]
 [ 86.  88. 137.  28.   5.]
 [ 50.  75.  89.  91.  57.]
 [  7.  46.  45.  25. 239.]]
[[169.  75.  84.  61.  14.]
 [ 37. 200.  83.  66.  38.]
 [114.  92. 164.  28.   5.]
 [ 67.  92.  89. 110.  66.]
 [  8.  62.  45.  26. 283.]]
[[209.  84.  91.  64.  14.]
 [ 45. 232.  85.  82.  42.]
 [132.  99. 193.  33.   5.]
 [ 8

In [ ]:
L = evaluation_classif_L(LDA_conf_mat)
N = evaluation_classif_N(LDA_conf_mat)
R = evaluation_classif_R(LDA_conf_mat)
S = evaluation_classif_S(LDA_conf_mat)
T = evaluation_classif_T(LDA_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST LDA JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost LDA JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost LDA JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost LDA JE ', prosecna_osetljivost)

# PROSECNA TACNOST LDA JE  0.7785209744846476
# PROSECNA specificnost LDA JE  0.8615708470535794
# PROSECNA preciznost LDA JE  0.4406708709991619
# PROSECNA osetljivost LDA JE  0.4463411576981079

PROSECNA TACNOST LDA JE  0.7785209744846476
PROSECNA specificnost LDA JE  0.8615708470535794
PROSECNA preciznost LDA JE  0.4406708709991619
PROSECNA osetljivost LDA JE  0.4463411576981079
