In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score,recall_score,f1_score
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [2]:
def evaluation_classif_L(conf_mat):
    TP = conf_mat[0,0]
    FP = conf_mat[1,0]+conf_mat[2,0]+conf_mat[3,0]+conf_mat[4,0]
    FN = conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]
    TN = conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [3]:
def evaluation_classif_N(conf_mat):
    TP = conf_mat[1,1]
    FP = conf_mat[0,1]+conf_mat[2,1]+conf_mat[3,1]+conf_mat[4,1]
    FN = conf_mat[1,0]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]
    TN = conf_mat[0,0]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[2,0]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,0]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [4]:
def evaluation_classif_R(conf_mat):
    TP = conf_mat[2,2]
    FP = conf_mat[0,2]+conf_mat[1,2]+conf_mat[3,2]+conf_mat[4,2]
    FN = conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,3]+conf_mat[2,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,3]+conf_mat[4,4]
    
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [5]:
def evaluation_classif_S(conf_mat):
    TP = conf_mat[3,3]
    FP = conf_mat[0,3]+conf_mat[1,3]+conf_mat[2,3]+conf_mat[4,3]
    FN = conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,4]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,4]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [6]:
def evaluation_classif_T(conf_mat):
    TP = conf_mat[4,4]
    FP = conf_mat[0,4]+conf_mat[1,4]+conf_mat[2,4]+conf_mat[3,4]
    FN = conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)
    

    return accuracy, precision, sensitivity, specificity

In [7]:
from google.colab import drive
drive.mount('/content/drive')
dataset_obuka_poc = pd.read_csv('drive/My Drive/diplomski2021/svi_preimenovani.csv')
#dataset_test = pd.read_csv('cookies_test.csv', header=0)
print(dataset_obuka_poc.shape)

dataset_obuka_poc.head()

Mounted at /content/drive
(9015, 386)


name  pcm_RMSenergy_sma_max  ...  F0_sma_de_kurtosis  class
0  '1BMZD01L__1100.wav'               0.126734  ...            5.684139      ?
1  '1BMZD02L__1100.wav'               0.104423  ...            6.739047      ?
2  '1BMZD03L__1100.wav'               0.115782  ...            5.404254      ?
3  '1BMZD04L__1100.wav'               0.109434  ...            5.881023      ?
4  '1BMZD05L__1100.wav'               0.113291  ...            6.588470      ?

[5 rows x 386 columns]

In [8]:
dataset_obuka_poc.loc[0:1752, 'class'] = 'L'
dataset_obuka_poc.loc[1753:3588, 'class'] = 'N'
dataset_obuka_poc.loc[3589:5341, 'class'] = 'R'
dataset_obuka_poc.loc[5342:7177, 'class'] = 'T'
dataset_obuka_poc.loc[7178:9016, 'class'] = 'S'

In [ ]:
print(dataset_obuka_poc.loc[5342:7178])

                           name  ...  class
5342       '4BMZD01T__1100.wav'  ...      T
5343       '4BMZD02T__1100.wav'  ...      T
5344       '4BMZD03T__1100.wav'  ...      T
5345       '4BMZD04T__1100.wav'  ...      T
5346       '4BMZD05T__1100.wav'  ...      T
...                         ...  ...    ...
7174  '4_4_1_SKMK30T__1052.wav'  ...      T
7175  '4_4_1_SKMK30T__1053.wav'  ...      T
7176  '4_4_1_SKMK30T__1057.wav'  ...      T
7177  '4_4_1_SKMK30T__1060.wav'  ...      T
7178       '5BMZD01S__1100.wav'  ...      S

[1837 rows x 386 columns]


In [9]:
lista_izbaci = ['1052', '1101','1102','1103','1104','1105','1100']
indeksi_izbaci = []
for i in range(0, len(lista_izbaci)):    
    indeksi1 = dataset_obuka_poc.loc[dataset_obuka_poc['name'].str.find(lista_izbaci[i]) !=-1].index
    dataset_obuka_poc.drop(indeksi1, axis = 0, inplace = True)
dataset_obuka = dataset_obuka_poc
print(dataset_obuka.head())
print(dataset_obuka.shape)

                          name  ...  class
348  '1_0_0_MMMD01L__0001.wav'  ...      L
349  '1_0_0_MMMD01L__0002.wav'  ...      L
350  '1_0_0_MMMD01L__0003.wav'  ...      L
351  '1_0_0_MMMD01L__0005.wav'  ...      L
352  '1_0_0_MMMD01L__1003.wav'  ...      L

[5 rows x 386 columns]
(6937, 386)


In [ ]:
print(dataset_obuka.shape)

(6935, 386)


In [10]:
X_obuka= dataset_obuka.iloc[:, :-1]
y_obuka = dataset_obuka.iloc[:, -1]

In [11]:
print('nedostajućih vrednosti ima: ', X_obuka.isnull().sum().sum())
print('oznake klasa su: ', y_obuka.unique())
pd.set_option('display.max_columns', None)
dataset_obuka.describe()

#za svaku emociju

nedostajućih vrednosti ima:  0
oznake klasa su:  ['L' 'N' 'R' 'T' 'S']


pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            6937.000000            6937.000000              6937.000000   
mean                0.050532               0.000094                 0.050438   
std                 0.055214               0.000240                 0.055094   
min                 0.000325               0.000000                 0.000325   
25%                 0.014310               0.000000                 0.014299   
50%                 0.027470               0.000000                 0.027457   
75%                 0.065080               0.000005                 0.065020   
max                 0.375493               0.001346                 0.375493   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               6937.000000               6937.000000   
mean                 138.807410                 12.793282   
std                   73.741383                 61.407888   
min                    9.000000                  0.000000   
25%                   85.000000                  0.000000   
50%                  123.000000                  0.000000   
75%                  175.000000                  0.000000   
max                  651.000000                605.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              6937.000000                6.937000e+03   
mean                  0.005730               -1.175783e-05   
std                   0.006152                2.379768e-05   
min                   0.000035               -2.664431e-04   
25%                   0.001799               -1.408064e-05   
50%                   0.003385               -4.922125e-06   
75%                   0.007170               -8.133701e-07   
max                   0.049019                7.377596e-05   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 6937.000000                  6.937000e+03   
mean                     0.007567                  1.683810e-04   
std                      0.008702                  3.954362e-04   
min                     -0.002039                  1.472844e-09   
25%                      0.002142                  6.585024e-06   
50%                      0.004382                  2.371220e-05   
75%                      0.009340                  1.190018e-04   
max                      0.082241                  4.506843e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               6937.000000                 6937.000000   
mean                   0.008777                    2.709976   
std                    0.009827                    1.072076   
min                    0.000040                    0.540959   
25%                    0.002599                    1.912802   
50%                    0.004934                    2.610086   
75%                    0.011062                    3.355209   
max                    0.068155                    8.184157   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 6937.000000                 6937.000000   
mean                    12.460084                    5.051606   
std                      8.168457                    3.048579   
min                      1.953328                   -5.798059   
25%                      6.690271                    2.477985   
50%                     10.524660                    4.893018   
75%                     15.833240                    7.209260   
max                     77.786890                   18.348910   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 6937.000000                   6937.000000   
mean                   -29.784193                     34.835799   
std                      3.668291                      4.221978   
min                    -41.459480                     12.670450   
25%                    -32.358860                     32.045110   
50%              

In [12]:
ljutnja = dataset_obuka[dataset_obuka['class'] == 'L']
pd.set_option('display.max_columns', None)
ljutnja.describe()

pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            1346.000000            1346.000000              1346.000000   
mean                0.068538               0.000098                 0.068440   
std                 0.061561               0.000249                 0.061422   
min                 0.005170               0.000000                 0.005170   
25%                 0.021320               0.000000                 0.021319   
50%                 0.043467               0.000000                 0.043452   
75%                 0.098049               0.000005                 0.098048   
max                 0.311929               0.001196                 0.311928   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               1346.000000               1346.000000   
mean                 112.450966                 12.551263   
std                   59.292353                 58.513678   
min                   19.000000                  0.000000   
25%                   69.000000                  0.000000   
50%                   98.000000                  0.000000   
75%                  146.000000                  0.000000   
max                  382.000000                456.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              1346.000000                 1346.000000   
mean                  0.008491                   -0.000025   
std                   0.007280                    0.000034   
min                   0.000728                   -0.000266   
25%                   0.003298                   -0.000035   
50%                   0.005475                   -0.000015   
75%                   0.012163                   -0.000006   
max                   0.049019                    0.000069   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 1346.000000                  1.346000e+03   
mean                     0.012104                  2.688494e-04   
std                      0.010824                  4.843620e-04   
min                     -0.000328                  7.604959e-07   
25%                      0.004325                  1.849604e-05   
50%                      0.007980                  5.789962e-05   
75%                      0.017275                  2.780175e-04   
max                      0.082241                  4.274992e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               1346.000000                 1346.000000   
mean                   0.012480                    2.361482   
std                    0.011161                    0.870872   
min                    0.000910                    0.545413   
25%                    0.004402                    1.712330   
50%                    0.007760                    2.280831   
75%                    0.016986                    2.899779   
max                    0.068155                    5.967304   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 1346.000000                 1346.000000   
mean                     9.873447                    4.755489   
std                      5.856724                    2.711647   
min                      1.953328                   -3.203491   
25%                      5.674635                    2.633803   
50%                      8.484641                    4.739502   
75%                     12.555285                    6.787346   
max                     46.493280                   12.545920   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 1346.000000                   1346.000000   
mean                   -29.525915                     34.281404   
std                      3.865321                      4.327143   
min                    -40.070710                     19.140260   
25%                    -32.202655                     31.412370   
50%              

In [13]:
neutral = dataset_obuka[dataset_obuka['class'] == 'N']
pd.set_option('display.max_columns', None)
neutral.describe()

pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            1416.000000            1416.000000              1416.000000   
mean                0.035590               0.000103                 0.035487   
std                 0.040503               0.000251                 0.040337   
min                 0.001713               0.000000                 0.001713   
25%                 0.011745               0.000000                 0.011721   
50%                 0.020983               0.000000                 0.020956   
75%                 0.041072               0.000005                 0.041072   
max                 0.264665               0.001346                 0.263799   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               1416.000000               1416.000000   
mean                 139.691384                 11.721751   
std                   69.496941                 60.505856   
min                   31.000000                  0.000000   
25%                   88.000000                  0.000000   
50%                  122.000000                  0.000000   
75%                  178.000000                  0.000000   
max                  437.000000                605.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              1416.000000                1.416000e+03   
mean                  0.003907               -5.483626e-06   
std                   0.003811                1.116352e-05   
min                   0.000415               -9.180216e-05   
25%                   0.001592               -7.773776e-06   
50%                   0.002602               -3.484560e-06   
75%                   0.004750               -4.724720e-07   
max                   0.027222                5.011114e-05   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 1416.000000                  1.416000e+03   
mean                     0.004866                  7.872508e-05   
std                      0.005016                  2.210144e-04   
min                      0.000238                  1.755832e-07   
25%                      0.001876                  5.057894e-06   
50%                      0.003271                  1.351035e-05   
75%                      0.005972                  4.531571e-05   
max                      0.043887                  1.920580e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               1416.000000                 1416.000000   
mean                   0.005987                    2.652362   
std                    0.006673                    1.087200   
min                    0.000431                    0.540959   
25%                    0.002259                    1.806110   
50%                    0.003734                    2.536453   
75%                    0.006816                    3.346230   
max                    0.043826                    7.648660   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 1416.000000                 1416.000000   
mean                    12.170571                    5.701071   
std                      8.108513                    3.226205   
min                      2.220437                   -1.763388   
25%                      6.228239                    2.924392   
50%                     10.226425                    5.512163   
75%                     15.698087                    8.055473   
max                     71.118650                   15.999660   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 1416.000000                   1416.000000   
mean                   -29.623763                     35.324834   
std                      3.625574                      4.222667   
min                    -40.334340                     22.246060   
25%                    -32.147728                     32.543427   
50%              

In [14]:
radost = dataset_obuka[dataset_obuka['class'] == 'R']
pd.set_option('display.max_columns', None)
radost.describe()

pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            1346.000000            1346.000000              1346.000000   
mean                0.061136               0.000095                 0.061041   
std                 0.057410               0.000244                 0.057295   
min                 0.000335               0.000000                 0.000335   
25%                 0.019951               0.000000                 0.019931   
50%                 0.037017               0.000000                 0.036878   
75%                 0.086978               0.000005                 0.086978   
max                 0.353374               0.001234                 0.353374   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               1346.000000               1346.000000   
mean                 133.812779                 17.471768   
std                   67.824137                 73.849830   
min                   11.000000                  0.000000   
25%                   82.000000                  0.000000   
50%                  119.000000                  0.000000   
75%                  172.000000                  0.000000   
max                  426.000000                564.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              1346.000000                 1346.000000   
mean                  0.007711                   -0.000015   
std                   0.006773                    0.000023   
min                   0.000035                   -0.000207   
25%                   0.003063                   -0.000021   
50%                   0.004757                   -0.000009   
75%                   0.010950                   -0.000002   
max                   0.039936                    0.000074   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 1346.000000                  1.346000e+03   
mean                     0.010217                  2.185401e-04   
std                      0.009315                  4.344656e-04   
min                      0.000027                  1.472844e-09   
25%                      0.003984                  1.447688e-05   
50%                      0.006578                  4.082352e-05   
75%                      0.014180                  2.249237e-04   
max                      0.062640                  4.506843e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               1346.000000                 1346.000000   
mean                   0.010931                    2.326622   
std                    0.010297                    0.945916   
min                    0.000040                    0.551513   
25%                    0.003865                    1.672011   
50%                    0.006525                    2.173216   
75%                    0.015351                    2.869312   
max                    0.067806                    6.646028   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 1346.000000                 1346.000000   
mean                    10.022900                    4.789422   
std                      6.591876                    3.121029   
min                      2.140378                   -1.448716   
25%                      5.551336                    2.191773   
50%                      8.161473                    4.361356   
75%                     12.602892                    6.898221   
max                     51.284690                   14.846000   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 1346.000000                   1346.000000   
mean                   -29.572186                     34.361607   
std                      3.595787                      4.200360   
min                    -40.129690                     12.670450   
25%                    -32.105802                     31.730552   
50%              

In [15]:
strah = dataset_obuka[dataset_obuka['class'] == 'S']
pd.set_option('display.max_columns', None)
strah.describe()

pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            1415.000000            1415.000000              1415.000000   
mean                0.063439               0.000095                 0.063345   
std                 0.064186               0.000242                 0.064082   
min                 0.000325               0.000000                 0.000325   
25%                 0.016798               0.000000                 0.016797   
50%                 0.036544               0.000000                 0.036544   
75%                 0.087459               0.000005                 0.087385   
max                 0.375493               0.001275                 0.375493   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               1415.000000               1415.000000   
mean                 137.108127                 10.202120   
std                   67.831685                 51.324302   
min                   16.000000                  0.000000   
25%                   87.000000                  0.000000   
50%                  123.000000                  0.000000   
75%                  172.000000                  0.000000   
max                  412.000000                409.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              1415.000000                1.415000e+03   
mean                  0.006566               -1.091840e-05   
std                   0.006593                2.607909e-05   
min                   0.000045               -2.291473e-04   
25%                   0.002189               -1.347510e-05   
50%                   0.003792               -5.278657e-06   
75%                   0.008654                2.755329e-07   
max                   0.045284                7.377596e-05   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 1415.000000                  1.415000e+03   
mean                     0.008254                  2.422595e-04   
std                      0.009164                  5.027104e-04   
min                      0.000057                  2.767067e-09   
25%                      0.002555                  9.095098e-06   
50%                      0.004940                  3.514051e-05   
75%                      0.010181                  2.016238e-04   
max                      0.076059                  4.343176e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               1415.000000                 1415.000000   
mean                   0.010852                    2.821368   
std                    0.011424                    1.001150   
min                    0.000053                    0.654152   
25%                    0.003049                    2.119163   
50%                    0.005988                    2.763980   
75%                    0.014361                    3.389582   
max                    0.066686                    6.950871   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 1415.000000                 1415.000000   
mean                    12.963804                    4.386243   
std                      7.629960                    2.807398   
min                      2.229873                   -5.798059   
25%                      7.611008                    2.132906   
50%                     11.382250                    3.981153   
75%                     16.270275                    6.459151   
max                     58.774410                   18.348910   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 1415.000000                   1415.000000   
mean                   -30.163364                     34.549608   
std                      3.620291                      3.993568   
min                    -41.459480                     14.298720   
25%                    -32.721555                     31.784445   
50%              

In [16]:
tuga = dataset_obuka[dataset_obuka['class'] == 'T']
pd.set_option('display.max_columns', None)
tuga.describe()

pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            1414.000000            1414.000000              1414.000000   
mean                0.025347               0.000081                 0.025266   
std                 0.031831               0.000212                 0.031693   
min                 0.001775               0.000000                 0.001775   
25%                 0.008185               0.000000                 0.008165   
50%                 0.014486               0.000000                 0.014486   
75%                 0.027347               0.000005                 0.027331   
max                 0.248178               0.001108                 0.247078   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               1414.000000               1414.000000   
mean                 169.466054                 12.236209   
std                   88.862521                 61.062932   
min                    9.000000                  0.000000   
25%                  105.000000                  0.000000   
50%                  147.000000                  0.000000   
75%                  205.000000                  0.000000   
max                  651.000000                598.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              1414.000000                1.414000e+03   
mean                  0.002205               -2.791076e-06   
std                   0.002478                6.714352e-06   
min                   0.000269               -5.690818e-05   
25%                   0.000908               -3.959386e-06   
50%                   0.001420               -1.515249e-06   
75%                   0.002327               -9.871161e-08   
max                   0.023348                5.648282e-05   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 1414.000000                  1.414000e+03   
mean                     0.002744                  4.084927e-05   
std                      0.003323                  1.447706e-04   
min                     -0.002039                  4.699351e-08   
25%                      0.001031                  1.775877e-06   
50%                      0.001716                  4.795380e-06   
75%                      0.003000                  1.651683e-05   
max                      0.032655                  1.889731e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               1414.000000                 1414.000000   
mean                   0.003921                    3.352852   
std                    0.005114                    1.093839   
min                    0.000221                    0.621922   
25%                    0.001350                    2.614168   
50%                    0.002219                    3.250348   
75%                    0.004130                    3.987837   
max                    0.043803                    8.184157   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 1414.000000                 1414.000000   
mean                    17.028152                    5.598507   
std                      9.806349                    3.118480   
min                      2.318190                   -5.260468   
25%                     10.410013                    2.974913   
50%                     14.667175                    5.738093   
75%                     21.288243                    7.717751   
max                     77.786890                   13.984460   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 1414.000000                   1414.000000   
mean                   -30.013080                     35.611587   
std                      3.593944                      4.199304   
min                    -39.733280                     18.448730   
25%                    -32.624255                     32.934475   
50%              

In [ ]:
L_ljutnja=sum(dataset_obuka['class'] == 'L')
print('Klasi L-ljutnja pripada: ',L_ljutnja, ' uzoraka')
N_neutral=sum(dataset_obuka['class'] == 'N')
print('Klasi N-neutralno pripada: ',N_neutral, ' uzoraka')
R_radost=sum(dataset_obuka['class'] == 'R')
print('Klasi R-radost pripada: ',R_radost, ' uzoraka')
S_strah=sum(dataset_obuka['class'] == 'S')
print('Klasi S-strah pripada: ',S_strah, ' uzoraka')
T_tuga=sum(dataset_obuka['class'] == 'T')
print('Klasi T-tuga pripada: ',T_tuga, ' uzoraka')

Klasi L-ljutnja pripada:  1346  uzoraka
Klasi N-neutralno pripada:  1414  uzoraka
Klasi R-radost pripada:  1346  uzoraka
Klasi S-strah pripada:  1415  uzoraka
Klasi T-tuga pripada:  1414  uzoraka


In [ ]:
bez_imena = dataset_obuka.drop(['name'], axis = 1)

In [ ]:
print(bez_imena.head())

     pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  ...  F0_sma_de_kurtosis  class
348               0.024221               0.000000  ...            4.763613      L
349               0.017863               0.000000  ...           12.084200      L
350               0.020618               0.000005  ...            7.861353      L
351               0.031197               0.000000  ...            5.890788      L
352               0.082126               0.000073  ...            8.007851      L

[5 rows x 385 columns]


In [ ]:
X_obuka= bez_imena.iloc[:, :-1]
y_obuka = bez_imena.iloc[:, -1]
# s = StandardScaler()
# X_std = s.fit_transform(X_obuka)

In [ ]:
# #ODABIR PARAMETARA ZA KNN METODU SA STANDARDIZOVANIM VREDNOSTIMA NA CELOM SKUPU POMOCU GRIDSEARCH
# from sklearn.model_selection import GridSearchCV
# parameters = {'metric':('euclidean', 'manhattan','chebyshev','hamming'), 'n_neighbors':[1,5,15,20,30,35],'weights':['uniform','distance']}
# knn = KNeighborsClassifier()
# clf=GridSearchCV(knn, parameters,cv = 10)
# clf.fit(X_std, y_obuka)
# print(clf.best_score_)
# print(clf.best_params_)

In [ ]:
# #ODABIR PARAMETARA ZA KNN METODU SA STANDARDIZOVANIM VREDNOSTIMA NA CELOM SKUPU - FOR PETLJA
#labels_y = y_obuka.unique()
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,15,20,30,35]:
     for m in ['euclidean', 'manhattan','chebyshev','hamming']:
         for l in ['uniform','distance']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:
                 pd.set_option('display.max_rows', None)
                 print(X_obuka.iloc[train_index,:].dtypes)
                 classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)  
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 classifier.fit(X_std1, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_std_test)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre k= 15  i m= manhattan weigth je: distance  tacnost je:  0.8734283967713363  a mat. konf. je:
# [[1.113e+03 5.100e+01 7.100e+01 8.700e+01 2.400e+01]
#  [1.300e+01 1.318e+03 1.400e+01 3.300e+01 3.800e+01]
#  [5.000e+01 8.200e+01 1.113e+03 9.100e+01 1.000e+01]
#  [5.200e+01 7.900e+01 4.200e+01 1.176e+03 6.600e+01]
#  [0.000e+00 3.600e+01 1.000e+00 3.800e+01 1.339e+03]]

za parametre k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7174540797019183  a mat. konf. je:
[[ 900.  101.  136.  179.   30.]
 [  58. 1102.   70.  107.   79.]
 [ 161.  135.  877.  164.    9.]
 [ 119.  150.  117.  925.  104.]
 [  11.  113.    9.  108. 1173.]]
za parametre k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7174540797019183  a mat. konf. je:
[[ 900.  101.  136.  179.   30.]
 [  58. 1102.   70.  107.   79.]
 [ 161.  135.  877.  164.    9.]
 [ 119.  150.  117.  925.  104.]
 [  11.  113.    9.  108. 1173.]]
za parametre k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.7367711699123803  a mat. konf. je:
[[ 920.   82.  133.  185.   26.]
 [  53. 1108.   78.   93.   84.]
 [ 129.  129.  904.  174.   10.]
 [ 127.  138.  113.  949.   88.]
 [  10.   91.    5.   78. 1230.]]
za parametre k= 1  i m= manhattan weigth je: distance  tacnost je:  0.7367711699123803  a mat. konf. je:
[[ 920.   82.  133.  185.   26.]
 [  53. 1108.   78.   93.   84.]
 [ 129.  129.  904

In [ ]:
lista = ['0001','0002','0003','0005','1003','1004','1005','1007','1008','1009','1011','1012','1014','1015','1016','1023','1027','1036','1045','1051','1053','1057','1060']
indeksi_svi = []
for i in range(0,len(lista)):
    indeksi = dataset_obuka[dataset_obuka['name'].str.find(lista[i]) !=-1].index
    indeksi_svi.append(indeksi)
#print(indeksi_svi)

#dataset_obuka.drop(['name'],axis = 1, inplace = True)
for i in range(0,len(lista)): 
  bez_imena = dataset_obuka.drop(['name'], axis = 1)
  vars()["g"+lista[i]]= bez_imena.loc[indeksi_svi[i]]

In [ ]:
print(g0001.head())

     pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  ...  F0_sma_de_kurtosis  class
348               0.024221                    0.0  ...            4.763613      L
372               0.024982                    0.0  ...            6.281379      L
396               0.027422                    0.0  ...            5.050955      L
420               0.037283                    0.0  ...            5.373823      L
444               0.033850                    0.0  ...            6.789674      L

[5 rows x 385 columns]


In [ ]:
print(g0001.index)
print(g0002.index)
print(g0003.shape)

Int64Index([ 348,  372,  396,  420,  444,  468,  492,  516,  540,  564,
            ...
            8775, 8799, 8823, 8847, 8871, 8895, 8919, 8943, 8967, 8991],
           dtype='int64', length=294)
Int64Index([ 349,  373,  397,  421,  445,  469,  493,  517,  541,  565,
            ...
            8776, 8800, 8824, 8848, 8872, 8896, 8920, 8944, 8968, 8992],
           dtype='int64', length=294)
(294, 385)


In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  X_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  X_test1_std = s.transform(X_test1)

  classifier_kon = KNeighborsClassifier(n_neighbors=15, metric='manhattan',weights='distance')
  classifier_kon.fit(X_obuka29_std, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test1_std) 
  #navedi tacne nazive umesto y_test1
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  fin_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(fin_conf_mat)
  #acc.append(np.mean(acc_tmp))

# [[578. 175. 252. 234. 107.]
#  [327. 363. 129. 258. 339.]
#  [289. 174. 523. 272.  88.]
#  [216. 214. 266. 441. 278.]
#  [ 63. 221.  33. 135. 962.]]

[[46.  5.  5.  1.  0.]
 [30. 14. 16.  0.  0.]
 [15.  8. 33.  1.  0.]
 [29.  0.  3. 28.  0.]
 [34.  4. 14.  5.  3.]]
[[86. 15.  9.  4.  0.]
 [70. 26. 16.  2.  6.]
 [42. 23. 47.  2.  0.]
 [48. 29.  4. 34.  5.]
 [40. 34. 14.  9. 23.]]
[[92. 23. 47.  9.  0.]
 [71. 43. 36. 22.  8.]
 [45. 62. 56.  8.  0.]
 [48. 43. 43. 36. 10.]
 [40. 36. 15. 11. 78.]]
[[ 99.  51.  53.  25.   0.]
 [ 74.  66.  36.  55.   9.]
 [ 59.  63.  86.  20.   0.]
 [ 54.  43.  44.  88.  11.]
 [ 40.  38.  15.  12. 135.]]
[[145.  53.  57.  28.   2.]
 [ 81.  83.  40.  60.  36.]
 [ 73.  71.  98.  24.  19.]
 [ 58.  58.  47.  97.  40.]
 [ 40.  38.  15.  12. 195.]]
[[158.  67.  62.  40.  17.]
 [ 82.  98.  49.  62.  71.]
 [ 78.  83. 113.  35.  35.]
 [ 60.  81.  49.  99.  73.]
 [ 40.  44.  15.  13. 250.]]
[[165.  77.  69.  74.  18.]
 [ 83. 131.  58.  74.  78.]
 [ 86.  83. 119.  80.  35.]
 [ 67.  81.  94. 105.  77.]
 [ 43.  70.  19.  21. 271.]]
[[195.  80.  83.  86.  18.]
 [ 96. 147.  60.  93.  90.]
 [ 93.  83. 168.  83.  35.]
 [ 8

In [ ]:
L = evaluation_classif_L(fin_conf_mat)
N = evaluation_classif_N(fin_conf_mat)
R = evaluation_classif_R(fin_conf_mat)
S = evaluation_classif_S(fin_conf_mat)
T = evaluation_classif_T(fin_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost JE ', prosecna_osetljivost)

# PROSECNA TACNOST JE  0.7653164192013839
# PROSECNA specificnost JE  0.853293824958613
# PROSECNA preciznost JE  0.40300050440073737
# PROSECNA osetljivost JE  0.41326707394576284

PROSECNA TACNOST JE  0.7653164192013839
PROSECNA specificnost JE  0.853293824958613
PROSECNA preciznost JE  0.40300050440073737
PROSECNA osetljivost JE  0.41326707394576284


In [ ]:
pca = PCA(n_components=None)
pca.fit(X_std)
plt.plot(np.cumsum(pca.explained_variance_ratio_))

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=125
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=125)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 125, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 125, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8516663131936907  a mat. konf. je:
# [[1.082e+03 5.700e+01 7.800e+01 1.020e+02 2.700e+01]
#  [2.100e+01 1.289e+03 1.400e+01 4.500e+01 4.700e+01]
#  [4.900e+01 8.300e+01 1.105e+03 1.010e+02 8.000e+00]
#  [5.900e+01 8.500e+01 4.700e+01 1.157e+03 6.700e+01]
#  [1.000e+00 6.300e+01 3.000e+00 7.200e+01 1.275e+03]]

za parametre  n_components= 125, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7266809719259286  a mat. konf. je:
[[ 914.   92.  140.  171.   29.]
 [  57. 1108.   60.  101.   90.]
 [ 155.  122.  892.  167.   10.]
 [ 124.  139.  124.  936.   92.]
 [  10.  108.    8.   97. 1191.]]
za parametre  n_components= 125, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7249520732229666  a mat. konf. je:
[[ 915.   95.  136.  171.   29.]
 [  58. 1097.   62.  106.   93.]
 [ 150.  116.  898.  172.   10.]
 [ 126.  137.  126.  933.   93.]
 [  12.  112.    8.   96. 1186.]]
za parametre  n_components= 125, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6900644984218471  a mat. konf. je:
[[ 872.  105.  142.  185.   42.]
 [  67. 1062.   76.  117.   94.]
 [ 167.  142.  833.  187.   17.]
 [ 141.  153.  129.  882.  110.]
 [  24.  134.    7.  111. 1138.]]
za parametre  n_components= 125, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6915070840142886  a mat. konf. je:
[[ 8

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=150
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=150)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 150, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))


# za parametre  n_components= 150, k= 30  i m= euclidean weigth je: distance  tacnost je:  0.8470518274552855  a mat. konf. je:
# [[1081.   55.   86.  103.   21.]
#  [  24. 1278.   18.   53.   43.]
#  [  49.   91. 1098.  100.    8.]
#  [  65.   87.   37. 1164.   62.]
#  [   3.   75.    2.   79. 1255.]]

za parametre  n_components= 150, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7196152550619409  a mat. konf. je:
[[ 907.   96.  136.  182.   25.]
 [  64. 1093.   64.  108.   87.]
 [ 148.  118.  890.  182.    8.]
 [ 126.  141.  119.  930.   99.]
 [  11.  117.    9.  105. 1172.]]
za parametre  n_components= 150, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.721635041231583  a mat. konf. je:
[[ 910.   94.  135.  179.   28.]
 [  58. 1101.   69.  106.   82.]
 [ 157.  118.  894.  169.    8.]
 [ 127.  139.  121.  930.   98.]
 [   8.  117.   10.  108. 1171.]]
za parametre  n_components= 150, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6811278698886768  a mat. konf. je:
[[ 860.  107.  135.  204.   40.]
 [  81. 1052.   75.  117.   91.]
 [ 171.  147.  809.  201.   18.]
 [ 137.  163.  127.  893.   95.]
 [  24.  152.    9.  118. 1111.]]
za parametre  n_components= 150, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6835772296867397  a mat. konf. je:
[[ 87

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=175
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=175)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 175, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))


# za parametre  n_components= 175, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8480600571378669  a mat. konf. je:
# [[1082.   55.   85.   98.   26.]
#  [  20. 1299.   17.   42.   38.]
#  [  56.   92. 1076.  113.    9.]
#  [  63.   86.   41. 1159.   66.]
#  [   0.   67.    3.   77. 1267.]]

za parametre  n_components= 175, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7155821284063358  a mat. konf. je:
[[ 903.   98.  138.  178.   29.]
 [  57. 1083.   76.  111.   89.]
 [ 157.  128.  883.  169.    9.]
 [ 116.  145.  119.  930.  105.]
 [  13.  116.    9.  111. 1165.]]
za parametre  n_components= 175, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7167346582332172  a mat. konf. je:
[[ 903.   95.  139.  178.   31.]
 [  58. 1087.   75.  109.   87.]
 [ 153.  130.  884.  170.    9.]
 [ 115.  144.  120.  933.  103.]
 [  12.  117.    9.  111. 1165.]]
za parametre  n_components= 175, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6749292014421697  a mat. konf. je:
[[ 857.  110.  133.  202.   44.]
 [  76. 1043.   68.  122.  107.]
 [ 177.  158.  827.  169.   15.]
 [ 155.  172.  135.  849.  104.]
 [  22.  147.   15.  124. 1106.]]
za parametre  n_components= 175, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6781017253639733  a mat. konf. je:
[[ 8

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=200
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=200)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 200, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))


# za parametre  n_components= 200, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8493554316320887  a mat. konf. je:
# [[1083.   58.   83.   98.   24.]
#  [  23. 1291.   18.   45.   39.]
#  [  53.   92. 1083.  108.   10.]
#  [  66.   82.   41. 1166.   60.]
#  [   0.   64.    3.   78. 1269.]]

za parametre  n_components= 200, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7168789583775175  a mat. konf. je:
[[ 901.  100.  136.  180.   29.]
 [  58. 1097.   72.  108.   81.]
 [ 155.  129.  879.  173.   10.]
 [ 120.  147.  118.  925.  105.]
 [  12.  113.    9.  109. 1171.]]
za parametre  n_components= 200, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7167352820090571  a mat. konf. je:
[[ 901.  101.  136.  179.   29.]
 [  58. 1097.   73.  110.   78.]
 [ 156.  130.  878.  172.   10.]
 [ 117.  149.  120.  924.  105.]
 [  12.  112.    9.  109. 1172.]]
za parametre  n_components= 200, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6766595556220916  a mat. konf. je:
[[ 849.  107.  132.  211.   47.]
 [  73. 1043.   75.  124.  101.]
 [ 165.  166.  835.  166.   14.]
 [ 151.  177.  122.  855.  110.]
 [  20.  150.   13.  119. 1112.]]
za parametre  n_components= 200, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6759386786764308  a mat. konf. je:
[[ 8

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
pca_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XPCA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XPCA_test1_std = s.transform(X_test1)

  pca = PCA(n_components=125)
  pca.fit(XPCA_obuka29_std)
  X_train_PCA = pca.transform(XPCA_obuka29_std)
  X_test_PCA=pca.transform(XPCA_test1_std)

  classifier_kon = KNeighborsClassifier(n_neighbors=20, metric='euclidean',weights='distance')
  classifier_kon.fit(X_train_PCA, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_PCA) 
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  pca_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(pca_conf_mat)

# [[549. 176. 239. 297.  85.]
#  [312. 366. 136. 287. 315.]
#  [289. 181. 517. 288.  71.]
#  [208. 230. 258. 466. 253.]
#  [ 55. 249.  43. 133. 934.]]

[[45.  4.  7.  1.  0.]
 [35.  9. 14.  2.  0.]
 [10.  9. 38.  0.  0.]
 [23.  2.  5. 30.  0.]
 [30.  5. 13.  9.  3.]]
[[87. 12. 10.  4.  1.]
 [77. 22. 17.  2.  2.]
 [43. 17. 51.  3.  0.]
 [40. 34.  6. 38.  2.]
 [39. 32. 13. 14. 22.]]
[[92. 22. 42. 14.  1.]
 [78. 38. 38. 23.  3.]
 [45. 59. 60.  6.  1.]
 [40. 51. 42. 41.  6.]
 [39. 39. 14. 16. 72.]]
[[ 98.  43.  47.  39.   1.]
 [ 82.  55.  39.  59.   5.]
 [ 61.  60.  80.  26.   1.]
 [ 49.  51.  42.  92.   6.]
 [ 39.  40.  14.  17. 130.]]
[[142.  44.  52.  42.   5.]
 [ 86.  81.  41.  62.  30.]
 [ 77.  63.  96.  32.  17.]
 [ 55.  67.  44. 104.  30.]
 [ 39.  40.  14.  17. 190.]]
[[156.  59.  59.  52.  18.]
 [ 86.  96.  47.  68.  65.]
 [ 82.  86. 108.  41.  27.]
 [ 55.  85.  47. 106.  69.]
 [ 39.  52.  15.  18. 238.]]
[[164.  69.  62.  90.  18.]
 [ 87. 121.  60.  81.  75.]
 [ 90.  86. 115.  85.  27.]
 [ 57.  87.  95. 111.  74.]
 [ 40.  78.  21.  22. 263.]]
[[202.  71.  67. 103.  19.]
 [100. 137.  62. 107.  80.]
 [ 97.  86. 163.  89.  27.]
 [ 7

In [ ]:
L = evaluation_classif_L(pca_conf_mat)
N = evaluation_classif_N(pca_conf_mat)
R = evaluation_classif_R(pca_conf_mat)
S = evaluation_classif_S(pca_conf_mat)
T = evaluation_classif_T(pca_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST PCA JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost PCA JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost PCA JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost PCA JE ', prosecna_osetljivost)

# PROSECNA TACNOST PCA JE  0.7632982557301426
# PROSECNA specificnost PCA JE  0.8520096056123918
# PROSECNA preciznost PCA JE  0.40130188585725823
# PROSECNA osetljivost PCA JE  0.4080633812706715

PROSECNA TACNOST PCA JE  0.7632982557301426
PROSECNA specificnost PCA JE  0.8520096056123918
PROSECNA preciznost PCA JE  0.40130188585725823
PROSECNA osetljivost PCA JE  0.4080633812706715


In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=4
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=4)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 4, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 4, k= 35  i m= euclidean weigth je: distance  tacnost je:  0.7252446240918864  a mat. konf. je:
# [[ 921.  112.  152.  134.   27.]
#  [  92. 1024.   88.  109.  103.]
#  [ 137.   90.  953.  149.   17.]
#  [ 106.  142.  106.  940.  121.]
#  [  19.  105.    7.   90. 1193.]]

za parametre  n_components= 4, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.6410581733348304  a mat. konf. je:
[[ 839.  124.  202.  151.   30.]
 [ 143.  873.   99.  154.  147.]
 [ 196.  102.  865.  162.   21.]
 [ 166.  160.  169.  786.  134.]
 [  33.  133.   18.  146. 1084.]]
za parametre  n_components= 4, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.6410581733348304  a mat. konf. je:
[[ 839.  124.  202.  151.   30.]
 [ 143.  873.   99.  154.  147.]
 [ 196.  102.  865.  162.   21.]
 [ 166.  160.  169.  786.  134.]
 [  33.  133.   18.  146. 1084.]]
za parametre  n_components= 4, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6400497357269692  a mat. konf. je:
[[ 825.  126.  205.  160.   30.]
 [ 133.  871.  106.  156.  150.]
 [ 193.  101.  869.  164.   19.]
 [ 164.  164.  167.  781.  139.]
 [  33.  142.   17.  128. 1094.]]
za parametre  n_components= 4, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6400497357269692  a mat. konf. je:
[[ 825.  126

In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=3
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=3)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 3, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 3, k= 35  i m= manhattan weigth je: uniform  tacnost je:  0.6967027209102137  a mat. konf. je:
# [[9.000e+02 1.270e+02 1.560e+02 1.420e+02 2.100e+01]
#  [9.500e+01 1.002e+03 9.900e+01 9.500e+01 1.250e+02]
#  [1.180e+02 1.280e+02 8.980e+02 1.900e+02 1.200e+01]
#  [1.330e+02 1.300e+02 1.500e+02 8.820e+02 1.200e+02]
#  [1.100e+01 1.410e+02 1.000e+00 1.100e+02 1.151e+03]]

za parametre  n_components= 3, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.6100621280736556  a mat. konf. je:
[[ 813.  135.  179.  196.   23.]
 [ 127.  840.  154.  119.  176.]
 [ 185.  155.  789.  200.   17.]
 [ 179.  128.  216.  745.  147.]
 [  26.  181.   16.  146. 1045.]]
za parametre  n_components= 3, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.6100621280736556  a mat. konf. je:
[[ 813.  135.  179.  196.   23.]
 [ 127.  840.  154.  119.  176.]
 [ 185.  155.  789.  200.   17.]
 [ 179.  128.  216.  745.  147.]
 [  26.  181.   16.  146. 1045.]]
za parametre  n_components= 3, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.611794561506377  a mat. konf. je:
[[ 825.  142.  167.  192.   20.]
 [ 126.  839.  145.  136.  170.]
 [ 182.  153.  793.  198.   20.]
 [ 191.  133.  211.  746.  134.]
 [  30.  178.   17.  148. 1041.]]
za parametre  n_components= 3, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.611794561506377  a mat. konf. je:
[[ 825.  142. 

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
LDA_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XLDA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XLDA_test1_std = s.transform(X_test1)

  lda = LinearDiscriminantAnalysis(n_components=4)
  lda.fit(XLDA_obuka29_std, y_obuka29)
  X_train_29_lda = lda.transform(XLDA_obuka29_std)
  X_test_29_lda = lda.transform(XLDA_test1_std)

  classifier_kon = KNeighborsClassifier(n_neighbors=35, metric='euclidean',weights='distance')
  classifier_kon.fit(X_train_29_lda, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_29_lda) 
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)
  
  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  LDA_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  
  print(LDA_conf_mat)

#   [[562. 196. 246. 248.  94.]
#  [213. 506. 192. 232. 273.]
#  [215. 211. 642. 186.  92.]
#  [215. 243. 206. 523. 228.]
#  [ 48. 194.  65. 125. 982.]]


[[11.  5. 40.  1.  0.]
 [ 0.  6. 53.  1.  0.]
 [ 0.  0. 57.  0.  0.]
 [ 0.  0. 38. 22.  0.]
 [ 1. 10. 46.  3.  0.]]
[[24. 39. 44.  2.  5.]
 [ 1. 57. 55.  5.  2.]
 [ 2. 47. 59.  4.  2.]
 [ 0. 31. 38. 39. 12.]
 [ 1. 17. 46. 12. 44.]]
[[ 33.  41.  83.   9.   5.]
 [  4. 105.  55.  14.   2.]
 [ 12.  61.  87.   9.   2.]
 [  2.  49.  64.  52.  13.]
 [  1.  25.  46.  19.  89.]]
[[ 33.  49.  85.  56.   5.]
 [  4. 111.  58.  65.   2.]
 [ 16.  61. 114.  35.   2.]
 [  5.  49.  64. 109.  13.]
 [  1.  33.  46.  20. 140.]]
[[ 90.  49.  85.  56.   5.]
 [ 26. 138.  61.  67.   8.]
 [ 57.  64. 127.  35.   2.]
 [ 25.  56.  74. 121.  24.]
 [  1.  33.  46.  20. 200.]]
[[116.  62.  97.  58.  11.]
 [ 27. 159.  65.  67.  44.]
 [ 59.  96. 144.  35.  10.]
 [ 27.  80.  75. 122.  58.]
 [  1.  38.  46.  20. 257.]]
[[158.  75.  98.  61.  11.]
 [ 31. 208.  65.  70.  50.]
 [ 90. 104. 164.  35.  10.]
 [ 47.  93.  75. 147.  62.]
 [  2.  51.  46.  20. 305.]]
[[199.  83. 105.  64.  11.]
 [ 34. 247.  65.  87.  53.]
 [101. 

In [ ]:
L = evaluation_classif_L(LDA_conf_mat)
N = evaluation_classif_N(LDA_conf_mat)
R = evaluation_classif_R(LDA_conf_mat)
S = evaluation_classif_S(LDA_conf_mat)
T = evaluation_classif_T(LDA_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST LDA JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost LDA JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost LDA JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost LDA JE ', prosecna_osetljivost)

# PROSECNA TACNOST LDA JE  0.7853827302868674
# PROSECNA specificnost LDA JE  0.8658185181421046
# PROSECNA preciznost LDA JE  0.4569878986863788
# PROSECNA osetljivost LDA JE  0.46318838062054046

PROSECNA TACNOST LDA JE  0.7853827302868674
PROSECNA specificnost LDA JE  0.8658185181421046
PROSECNA preciznost LDA JE  0.4569878986863788
PROSECNA osetljivost LDA JE  0.46318838062054046
