In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score,recall_score,f1_score
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
def evaluation_classif_L(conf_mat):
    TP = conf_mat[0,0]
    FP = conf_mat[1,0]+conf_mat[2,0]+conf_mat[3,0]+conf_mat[4,0]
    FN = conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]
    TN = conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]

    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)


    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_N(conf_mat):
    TP = conf_mat[1,1]
    FP = conf_mat[0,1]+conf_mat[2,1]+conf_mat[3,1]+conf_mat[4,1]
    FN = conf_mat[1,0]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[1,4]
    TN = conf_mat[0,0]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[2,0]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[2,4]+conf_mat[3,0]+conf_mat[3,2]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,2]+conf_mat[4,3]+conf_mat[4,4]

    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)


    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_R(conf_mat):
    TP = conf_mat[2,2]
    FP = conf_mat[0,2]+conf_mat[1,2]+conf_mat[3,2]+conf_mat[4,2]
    FN = conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,3]+conf_mat[2,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,3]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,3]+conf_mat[1,4]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,3]+conf_mat[3,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,3]+conf_mat[4,4]

    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)


    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_S(conf_mat):
    TP = conf_mat[3,3]
    FP = conf_mat[0,3]+conf_mat[1,3]+conf_mat[2,3]+conf_mat[4,3]
    FN = conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,4]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,4]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,4]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,4]+conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,4]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)


    return accuracy, precision, sensitivity, specificity

In [ ]:
def evaluation_classif_T(conf_mat):
    TP = conf_mat[4,4]
    FP = conf_mat[0,4]+conf_mat[1,4]+conf_mat[2,4]+conf_mat[3,4]
    FN = conf_mat[4,0]+conf_mat[4,1]+conf_mat[4,2]+conf_mat[4,3]
    TN = conf_mat[0,0]+conf_mat[0,1]+conf_mat[0,2]+conf_mat[0,3]+conf_mat[1,0]+conf_mat[1,1]+conf_mat[1,2]+conf_mat[1,3]+conf_mat[2,0]+conf_mat[2,1]+conf_mat[2,2]+conf_mat[2,3]+conf_mat[3,0]+conf_mat[3,1]+conf_mat[3,2]+conf_mat[3,3]
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    precision = TP/(TP+FP)
    sensitivity = TP/(TP+FN)
    specificity = TN/(TN+FP)


    return accuracy, precision, sensitivity, specificity

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
dataset_obuka_poc = pd.read_csv('drive/My Drive/diplomski2021/svi_preimenovani.csv')
#dataset_test = pd.read_csv('cookies_test.csv', header=0)
print(dataset_obuka_poc.shape)
pd.set_option('display.max_columns', None)

dataset_obuka_poc.head()

Mounted at /content/drive
(9015, 386)


name  pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  \
0  '1BMZD01L__1100.wav'               0.126734               0.000055   
1  '1BMZD02L__1100.wav'               0.104423               0.000002   
2  '1BMZD03L__1100.wav'               0.115782               0.000015   
3  '1BMZD04L__1100.wav'               0.109434               0.000024   
4  '1BMZD05L__1100.wav'               0.113291               0.000020   

   pcm_RMSenergy_sma_range  pcm_RMSenergy_sma_maxPos  \
0                 0.126679                     112.0   
1                 0.104421                     353.0   
2                 0.115767                     246.0   
3                 0.109410                     312.0   
4                 0.113271                     222.0   

   pcm_RMSenergy_sma_minPos  pcm_RMSenergy_sma_amean  \
0                       0.0                 0.016041   
1                       0.0                 0.011477   
2                       0.0                 0.008997   
3                       0.0                 0.013651   
4                       0.0                 0.020900   

   pcm_RMSenergy_sma_linregc1  pcm_RMSenergy_sma_linregc2  \
0                   -0.000043                    0.024348   
1                   -0.000011                    0.014350   
2                   -0.000004                    0.010173   
3                    0.000008                    0.011610   
4                   -0.000034                    0.028620   

   pcm_RMSenergy_sma_linregerrQ  pcm_RMSenergy_sma_stddev  \
0                      0.000462                  0.022029   
1                      0.000352                  0.018844   
2                      0.000225                  0.015031   
3                      0.000288                  0.017020   
4                      0.000760                  0.027932   

   pcm_RMSenergy_sma_skewness  pcm_RMSenergy_sma_kurtosis  \
0                    2.142594                    8.407606   
1                    2.225843                    8.098756   
2                    3.572816                   19.761600   
3                    2.228274                   10.287780   
4                    1.439333                    4.118413   

   pcm_fftMag_mfcc_sma[1]_max  pcm_fftMag_mfcc_sma[1]_min  \
0                   -1.844059                   -27.03705   
1                    0.974885                   -34.26795   
2                   -0.425950                   -32.38249   
3                   -2.629931                   -34.82336   
4                    0.067662                   -30.33575   

   pcm_fftMag_mfcc_sma[1]_range  pcm_fftMag_mfcc_sma[1]_maxPos  \
0                      25.19299                          177.0   
1                      35.24283                          398.0   
2                      31.95654                          269.0   
3                      32.19343                          197.0   
4                      30.40341                          253.0   

   pcm_fftMag_mfcc_sma[1]_minPos  pcm_fftMag_mfcc_sma[1]_amean  \
0                          103.0                     -14.56909   
1                          340.0                     -16.39657   
2                          380.0                     -16.17110   
3                           91.0                     -16.17163   
4                          391.0                     -15.60746   

   pcm_fftMag_mfcc_sma[1]_linregc1  pcm_fftMag_mfcc_sma[1]_linregc2  \
0                         0.013259                        -17.10163   
1                         0.005342                        -17.76143   
2                        -0.001923                        -15.65093   
3                         0.003701                        -17.08580   
4                         0.005014                        -16.74320   

   pcm_fftMag_mfcc_sma[1]_linregerrQ  pcm_fftMag_mfcc_sma[1]_stddev  \
0                           27.15517                       5.413343   
1                           43.62640                       6.652050   
2   

In [ ]:


print(df.head())

In [ ]:
dataset_obuka_poc.loc[0:1752, 'class'] = 'L'
dataset_obuka_poc.loc[1753:3588, 'class'] = 'N'
dataset_obuka_poc.loc[3589:5341, 'class'] = 'R'
dataset_obuka_poc.loc[5342:7177, 'class'] = 'T'
dataset_obuka_poc.loc[7178:9016, 'class'] = 'S'


In [ ]:
lista_izbaci = ['1052', '1101','1102','1103','1104','1105','1100']
indeksi_izbaci = []
for i in range(0, len(lista_izbaci)):
    indeksi1 = dataset_obuka_poc.loc[dataset_obuka_poc['name'].str.find(lista_izbaci[i]) !=-1].index
    dataset_obuka_poc.drop(indeksi1, axis = 0, inplace = True)
dataset_obuka = dataset_obuka_poc
print(dataset_obuka.head())
print(dataset_obuka.shape)

                          name  pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  \
348  '1_0_0_MMMD01L__0001.wav'               0.024221               0.000000   
349  '1_0_0_MMMD01L__0002.wav'               0.017863               0.000000   
350  '1_0_0_MMMD01L__0003.wav'               0.020618               0.000005   
351  '1_0_0_MMMD01L__0005.wav'               0.031197               0.000000   
352  '1_0_0_MMMD01L__1003.wav'               0.082126               0.000073   

     pcm_RMSenergy_sma_range  pcm_RMSenergy_sma_maxPos  \
348                 0.024221                      79.0   
349                 0.017863                     270.0   
350                 0.020613                     310.0   
351                 0.031197                     254.0   
352                 0.082053                      90.0   

     pcm_RMSenergy_sma_minPos  pcm_RMSenergy_sma_amean  \
348                       0.0                 0.003874   
349                       0.0                 0.002127

In [ ]:
X_obuka= dataset_obuka.iloc[:, :-1]
y_obuka = dataset_obuka.iloc[:, -1]

In [ ]:
print('nedostajućih vrednosti ima: ', X_obuka.isnull().sum().sum())
print('oznake klasa su: ', y_obuka.unique())
pd.set_option('display.max_columns', None)
dataset_obuka.describe()

nedostajućih vrednosti ima:  0
oznake klasa su:  ['L' 'N' 'R' 'T' 'S']


pcm_RMSenergy_sma_max  pcm_RMSenergy_sma_min  pcm_RMSenergy_sma_range  \
count            6937.000000            6937.000000              6937.000000   
mean                0.050532               0.000094                 0.050438   
std                 0.055214               0.000240                 0.055094   
min                 0.000325               0.000000                 0.000325   
25%                 0.014310               0.000000                 0.014299   
50%                 0.027470               0.000000                 0.027457   
75%                 0.065080               0.000005                 0.065020   
max                 0.375493               0.001346                 0.375493   

       pcm_RMSenergy_sma_maxPos  pcm_RMSenergy_sma_minPos  \
count               6937.000000               6937.000000   
mean                 138.807410                 12.793282   
std                   73.741383                 61.407888   
min                    9.000000                  0.000000   
25%                   85.000000                  0.000000   
50%                  123.000000                  0.000000   
75%                  175.000000                  0.000000   
max                  651.000000                605.000000   

       pcm_RMSenergy_sma_amean  pcm_RMSenergy_sma_linregc1  \
count              6937.000000                6.937000e+03   
mean                  0.005730               -1.175783e-05   
std                   0.006152                2.379768e-05   
min                   0.000035               -2.664431e-04   
25%                   0.001799               -1.408064e-05   
50%                   0.003385               -4.922125e-06   
75%                   0.007170               -8.133701e-07   
max                   0.049019                7.377596e-05   

       pcm_RMSenergy_sma_linregc2  pcm_RMSenergy_sma_linregerrQ  \
count                 6937.000000                  6.937000e+03   
mean                     0.007567                  1.683810e-04   
std                      0.008702                  3.954362e-04   
min                     -0.002039                  1.472844e-09   
25%                      0.002142                  6.585024e-06   
50%                      0.004382                  2.371220e-05   
75%                      0.009340                  1.190018e-04   
max                      0.082241                  4.506843e-03   

       pcm_RMSenergy_sma_stddev  pcm_RMSenergy_sma_skewness  \
count               6937.000000                 6937.000000   
mean                   0.008777                    2.709976   
std                    0.009827                    1.072076   
min                    0.000040                    0.540959   
25%                    0.002599                    1.912802   
50%                    0.004934                    2.610086   
75%                    0.011062                    3.355209   
max                    0.068155                    8.184157   

       pcm_RMSenergy_sma_kurtosis  pcm_fftMag_mfcc_sma[1]_max  \
count                 6937.000000                 6937.000000   
mean                    12.460084                    5.051606   
std                      8.168457                    3.048579   
min                      1.953328                   -5.798059   
25%                      6.690271                    2.477985   
50%                     10.524660                    4.893018   
75%                     15.833240                    7.209260   
max                     77.786890                   18.348910   

       pcm_fftMag_mfcc_sma[1]_min  pcm_fftMag_mfcc_sma[1]_range  \
count                 6937.000000                   6937.000000   
mean                   -29.784193                     34.835799   
std                      3.668291                      4.221978   
min                    -41.459480                     12.670450   
25%                    -32.358860                     32.045110   
50%              

In [ ]:
dataset_obuka.drop(['pcm_RMSenergy_sma_minPos','pcm_zcr_sma_maxPos','voiceProb_sma_minPos', 'F0_sma_min','F0_sma_minPos'],axis = 1,inplace = True)
print(dataset_obuka.shape)

(6937, 381)


In [ ]:
bez_imena = dataset_obuka.drop(['name'], axis = 1)
print(bez_imena.shape)

(6937, 380)


In [ ]:
X_obuka= bez_imena.iloc[:, :-1]
y_obuka = bez_imena.iloc[:, -1]


In [ ]:
# #ODABIR PARAMETARA ZA KNN METODU SA STANDARDIZOVANIM VREDNOSTIMA NA CELOM SKUPU - FOR PETLJA
#labels_y = y_obuka.unique()
labels_y = ['L', 'N', 'R', 'S', 'T']
s = StandardScaler()
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,15,20,30,35]:
     for m in ['euclidean', 'manhattan','chebyshev','hamming']:
         for l in ['uniform','distance']:
             indexes = kf.split(X_obuka, y_obuka)
             acc_tmp = []
             fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
             for train_index, test_index in indexes:

                 classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                 X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                 X_std_test = s.transform(X_obuka.iloc[test_index,:])
                 classifier.fit(X_std1, y_obuka.iloc[train_index])
                 y_pred = classifier.predict(X_std_test)
                 acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                 fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
             print('za parametre k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
             print(fin_conf_mat)
             acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre k= 15  i m= manhattan weigth je: distance  tacnost je:  0.8750144508069579  a mat. konf. je:
# [[1.121e+03 4.600e+01 6.900e+01 8.400e+01 2.600e+01]
#  [1.300e+01 1.317e+03 1.400e+01 3.300e+01 3.900e+01]
#  [5.000e+01 8.300e+01 1.114e+03 9.000e+01 9.000e+00]
#  [5.200e+01 7.700e+01 4.200e+01 1.178e+03 6.600e+01]
#  [0.000e+00 3.500e+01 1.000e+00 3.800e+01 1.340e+03]]

pcm_RMSenergy_sma_max                    float64
pcm_RMSenergy_sma_min                    float64
pcm_RMSenergy_sma_range                  float64
pcm_RMSenergy_sma_maxPos                 float64
pcm_RMSenergy_sma_amean                  float64
pcm_RMSenergy_sma_linregc1               float64
pcm_RMSenergy_sma_linregc2               float64
pcm_RMSenergy_sma_linregerrQ             float64
pcm_RMSenergy_sma_stddev                 float64
pcm_RMSenergy_sma_skewness               float64
pcm_RMSenergy_sma_kurtosis               float64
pcm_fftMag_mfcc_sma[1]_max               float64
pcm_fftMag_mfcc_sma[1]_min               float64
pcm_fftMag_mfcc_sma[1]_range             float64
pcm_fftMag_mfcc_sma[1]_maxPos            float64
pcm_fftMag_mfcc_sma[1]_minPos            float64
pcm_fftMag_mfcc_sma[1]_amean             float64
pcm_fftMag_mfcc_sma[1]_linregc1          float64
pcm_fftMag_mfcc_sma[1]_linregc2          float64
pcm_fftMag_mfcc_sma[1]_linregerrQ        float64
pcm_fftMag_mfcc_sma[

KeyboardInterrupt: ignored

In [ ]:
lista = ['0001','0002','0003','0005','1003','1004','1005','1007','1008','1009','1011','1012','1014','1015','1016','1023','1027','1036','1045','1051','1053','1057','1060']
indeksi_svi = []
for i in range(0,len(lista)):
    indeksi = dataset_obuka[dataset_obuka['name'].str.find(lista[i]) !=-1].index
    indeksi_svi.append(indeksi)
#print(indeksi_svi)

#dataset_obuka.drop(['name'],axis = 1, inplace = True)
for i in range(0,len(lista)):
  bez_imena = dataset_obuka.drop(['name'], axis = 1)
  vars()["g"+lista[i]]= bez_imena.loc[indeksi_svi[i]]

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  X_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  X_test1_std = s.transform(X_test1)

  classifier_kon = KNeighborsClassifier(n_neighbors=15, metric='manhattan',weights='distance')
  classifier_kon.fit(X_obuka29_std, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test1_std)
  #navedi tacne nazive umesto y_test1
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)

  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  fin_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)

  print(fin_conf_mat)
# [[579. 173. 251. 232. 111.]
#  [325. 366. 132. 256. 337.]
#  [284. 173. 525. 273.  91.]
#  [222. 214. 265. 438. 276.]
#  [ 63. 223.  32. 136. 960.]]

[[46.  5.  5.  1.  0.]
 [30. 14. 16.  0.  0.]
 [15.  7. 34.  1.  0.]
 [29.  0.  3. 28.  0.]
 [34.  4. 14.  5.  3.]]
[[86. 15.  9.  4.  0.]
 [70. 26. 16.  2.  6.]
 [42. 22. 48.  2.  0.]
 [48. 29.  4. 34.  5.]
 [40. 34. 14.  9. 23.]]
[[92. 23. 47.  9.  0.]
 [71. 43. 37. 21.  8.]
 [45. 61. 57.  8.  0.]
 [48. 43. 43. 36. 10.]
 [40. 36. 15. 11. 78.]]
[[ 99.  51.  53.  25.   0.]
 [ 74.  66.  37.  54.   9.]
 [ 59.  62.  87.  20.   0.]
 [ 54.  43.  44.  88.  11.]
 [ 40.  38.  15.  12. 135.]]
[[147.  53.  55.  28.   2.]
 [ 80.  88.  40.  59.  33.]
 [ 73.  72.  97.  25.  18.]
 [ 59.  56.  49.  97.  39.]
 [ 40.  38.  15.  12. 195.]]
[[157.  67.  62.  40.  18.]
 [ 81. 103.  49.  62.  67.]
 [ 78.  85. 113.  33.  35.]
 [ 61.  80.  51.  99.  71.]
 [ 40.  46.  15.  13. 248.]]
[[164.  77.  70.  73.  19.]
 [ 82. 136.  58.  74.  74.]
 [ 86.  85. 119.  78.  35.]
 [ 68.  80.  96. 105.  75.]
 [ 43.  72.  19.  21. 269.]]
[[194.  80.  84.  85.  19.]
 [ 95. 152.  60.  93.  86.]
 [ 94.  85. 167.  81.  35.]
 [ 8

In [ ]:
L = evaluation_classif_L(fin_conf_mat)
N = evaluation_classif_N(fin_conf_mat)
R = evaluation_classif_R(fin_conf_mat)
S = evaluation_classif_S(fin_conf_mat)
T = evaluation_classif_T(fin_conf_mat)

print('Tacnost za klasu L je: ', L[0])
print('Tacnost za klasu N je: ', N[0])
print('Tacnost za klasu R je: ', R[0])
print('Tacnost za klasu S je: ', S[0])
print('Tacnost za klasu T je: ', T[0])

print('Specificnost za klasu L je: ', L[3])
print('Specificnost za klasu N je: ', N[3])
print('Specificnost za klasu R je: ', R[3])
print('Specificnost za klasu S je: ', S[3])
print('Specificnost za klasu T je: ', T[3])

print('Preciznost za klasu L je: ' , L[1])
print('Preciznost za klasu N je: ' , N[1])
print('Preciznost za klasu R je: ' , R[1])
print('Preciznost za klasu S je: ' , S[1])
print('Preciznost za klasu T je: ' , T[1])

print('Osetljivost za klasu L je: ' , L[2])
print('Osetljivost za klasu N je: ' , N[2])
print('Osetljivost za klasu R je: ' , R[2])
print('Osetljivost za klasu S je: ' , S[2])
print('Osetljivost za klasu T je: ' , T[2])

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost JE ', prosecna_osetljivost)

# PROSECNA TACNOST JE  0.7653740810148479
# PROSECNA specificnost JE  0.8533296229682803
# PROSECNA preciznost JE  0.4032465641578401
# PROSECNA osetljivost JE  0.4134296542896828

PROSECNA TACNOST JE  0.7653740810148479
PROSECNA specificnost JE  0.8533296229682803
PROSECNA preciznost JE  0.4032465641578401
PROSECNA osetljivost JE  0.4134296542896828


In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=125
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=125)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 125, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 125, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8493587584365683  a mat. konf. je:
# [[1.080e+03 5.800e+01 8.600e+01 9.600e+01 2.600e+01]
#  [1.800e+01 1.291e+03 1.900e+01 4.300e+01 4.500e+01]
#  [5.500e+01 8.400e+01 1.097e+03 1.010e+02 9.000e+00]
#  [6.300e+01 8.700e+01 4.900e+01 1.143e+03 7.300e+01]
#  [1.000e+00 5.900e+01 3.000e+00 7.000e+01 1.281e+03]]

za parametre  n_components= 125, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7223548785508439  a mat. konf. je:
[[ 916.   89.  134.  176.   31.]
 [  60. 1102.   66.  102.   86.]
 [ 154.  122.  899.  162.    9.]
 [ 125.  140.  130.  918.  102.]
 [  13.  115.    6.  104. 1176.]]
za parametre  n_components= 125, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7239398929600659  a mat. konf. je:
[[ 913.   94.  139.  172.   28.]
 [  56. 1107.   64.  103.   86.]
 [ 159.  117.  894.  170.    6.]
 [ 121.  143.  127.  927.   97.]
 [  12.  114.    8.   99. 1181.]]
za parametre  n_components= 125, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6920849083673292  a mat. konf. je:
[[ 870.  107.  147.  190.   32.]
 [  64. 1059.   76.  123.   94.]
 [ 177.  133.  844.  178.   14.]
 [ 151.  158.  124.  877.  105.]
 [  18.  133.    9.  103. 1151.]]
za parametre  n_components= 125, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6916505524574689  a mat. konf. je:
[[ 8

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=150
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=150)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 150, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 150, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8496456953229288  a mat. konf. je:
# [[1.092e+03 5.600e+01 8.200e+01 9.000e+01 2.600e+01]
#  [2.300e+01 1.290e+03 1.500e+01 4.600e+01 4.200e+01]
#  [5.200e+01 9.100e+01 1.087e+03 1.080e+02 8.000e+00]
#  [6.200e+01 8.100e+01 4.800e+01 1.157e+03 6.700e+01]
#  [1.000e+00 6.800e+01 3.000e+00 7.400e+01 1.268e+03]]

za parametre  n_components= 150, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7199038553505412  a mat. konf. je:
[[ 900.   92.  138.  190.   26.]
 [  55. 1087.   77.  110.   87.]
 [ 158.  119.  893.  169.    7.]
 [ 121.  135.  124.  938.   97.]
 [   9.  116.   10.  103. 1176.]]
za parametre  n_components= 150, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7230759634217847  a mat. konf. je:
[[ 910.   91.  135.  182.   28.]
 [  58. 1093.   73.  110.   82.]
 [ 151.  118.  904.  166.    7.]
 [ 123.  137.  124.  933.   98.]
 [  10.  113.    9.  106. 1176.]]
za parametre  n_components= 150, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6853079997172217  a mat. konf. je:
[[ 873.  104.  139.  196.   34.]
 [  72. 1076.   62.  116.   90.]
 [ 173.  158.  814.  186.   15.]
 [ 153.  166.  125.  869.  102.]
 [  19.  141.   12.  120. 1122.]]
za parametre  n_components= 150, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.68415713329258  a mat. konf. je:
[[ 871

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=175
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=175)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 175, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 175, k= 20  i m= euclidean weigth je: distance  tacnost je:  0.8489256500783877  a mat. konf. je:
# [[1090.   58.   82.   92.   24.]
#  [  21. 1292.   18.   45.   40.]
#  [  56.   96. 1081.  105.    8.]
#  [  72.   79.   41. 1156.   67.]
#  [   0.   63.    3.   78. 1270.]]

za parametre  n_components= 175, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7161562101043369  a mat. konf. je:
[[ 897.   98.  139.  182.   30.]
 [  55. 1087.   74.  113.   87.]
 [ 152.  126.  888.  170.   10.]
 [ 118.  145.  123.  923.  106.]
 [  11.  115.    9.  106. 1173.]]
za parametre  n_components= 175, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7161568338801767  a mat. konf. je:
[[ 903.   97.  140.  176.   30.]
 [  54. 1084.   76.  114.   88.]
 [ 152.  129.  885.  170.   10.]
 [ 115.  146.  126.  923.  105.]
 [  11.  114.   10.  106. 1173.]]
za parametre  n_components= 175, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.680552540638996  a mat. konf. je:
[[ 854.  109.  146.  194.   43.]
 [  76. 1065.   70.  117.   88.]
 [ 174.  165.  809.  184.   14.]
 [ 154.  166.  114.  873.  108.]
 [  18.  143.    9.  124. 1120.]]
za parametre  n_components= 175, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6814183415047967  a mat. konf. je:
[[ 86

In [ ]:
#TRAZENJE OPTIMALNOG BROJA KOMPONENTI ZA PCA, N_KOMP=200
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev','hamming']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    pca = PCA(n_components=200)
                    pca.fit(X_std1)
                    X_train_r = pca.transform(X_std1)
                    X_test_r=pca.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 200, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 200, k= 30  i m= euclidean weigth je: distance  tacnost je:  0.8474855595893059  a mat. konf. je:
# [[1.076e+03 6.200e+01 9.100e+01 9.700e+01 2.000e+01]
#  [2.100e+01 1.292e+03 1.500e+01 5.000e+01 3.800e+01]
#  [5.300e+01 9.500e+01 1.086e+03 1.050e+02 7.000e+00]
#  [6.400e+01 8.300e+01 4.500e+01 1.161e+03 6.200e+01]
#  [1.000e+00 6.400e+01 3.000e+00 8.200e+01 1.264e+03]]

za parametre  n_components= 200, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.7167340344573774  a mat. konf. je:
[[ 900.   98.  138.  181.   29.]
 [  57. 1091.   72.  113.   83.]
 [ 156.  123.  882.  175.   10.]
 [ 117.  147.  120.  926.  105.]
 [  12.  112.    9.  108. 1173.]]
za parametre  n_components= 200, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.7154374124114758  a mat. konf. je:
[[ 894.   99.  139.  184.   30.]
 [  57. 1090.   71.  114.   84.]
 [ 156.  124.  882.  174.   10.]
 [ 118.  147.  121.  923.  106.]
 [  12.  112.    9.  107. 1174.]]
za parametre  n_components= 200, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6759393024522707  a mat. konf. je:
[[ 850.  105.  147.  205.   39.]
 [  78. 1047.   73.  121.   97.]
 [ 178.  167.  806.  184.   11.]
 [ 145.  167.  118.  869.  116.]
 [  20.  149.   10.  118. 1117.]]
za parametre  n_components= 200, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6772371720498521  a mat. konf. je:
[[ 8

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
pca_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XPCA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XPCA_test1_std = s.transform(X_test1)

  pca = PCA(n_components=150)
  pca.fit(XPCA_obuka29_std)
  X_train_PCA = pca.transform(XPCA_obuka29_std)
  X_test_PCA=pca.transform(XPCA_test1_std)

  classifier_kon = KNeighborsClassifier(n_neighbors=20, metric='euclidean',weights='distance')
  classifier_kon.fit(X_train_PCA, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_PCA)
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)

  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  pca_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)

  print(pca_conf_mat)
# [[558. 180. 232. 294.  82.]
#  [316. 388. 136. 308. 268.]
#  [310. 183. 501. 291.  61.]
#  [248. 214. 251. 466. 236.]
#  [ 57. 252.  38. 148. 919.]]

[[50.  3.  3.  1.  0.]
 [30. 12. 17.  1.  0.]
 [11.  8. 38.  0.  0.]
 [28.  1.  2. 29.  0.]
 [30.  7. 12.  9.  2.]]
[[94. 11.  5.  3.  1.]
 [72. 22. 19.  5.  2.]
 [44. 16. 51.  3.  0.]
 [55. 27.  3. 33.  2.]
 [39. 35. 12. 15. 19.]]
[[101.  17.  38.  14.   1.]
 [ 73.  44.  40.  20.   3.]
 [ 48.  57.  59.   6.   1.]
 [ 55.  43.  41.  35.   6.]
 [ 39.  41.  13.  16.  71.]]
[[107.  39.  44.  37.   1.]
 [ 77.  61.  41.  56.   5.]
 [ 63.  59.  80.  25.   1.]
 [ 63.  43.  41.  87.   6.]
 [ 39.  42.  13.  17. 129.]]
[[150.  40.  49.  40.   6.]
 [ 82.  90.  43.  59.  26.]
 [ 82.  66.  92.  31.  14.]
 [ 71.  56.  45.  98.  30.]
 [ 39.  42.  13.  17. 189.]]
[[165.  51.  57.  53.  18.]
 [ 82. 107.  56.  65.  52.]
 [ 89.  84. 106.  40.  25.]
 [ 72.  77.  50. 101.  62.]
 [ 39.  56.  14.  18. 235.]]
[[173.  69.  59.  84.  18.]
 [ 83. 137.  65.  78.  61.]
 [ 97.  84. 113.  84.  25.]
 [ 74.  78.  99. 105.  68.]
 [ 40.  83.  20.  22. 259.]]
[[203.  73.  71.  97.  18.]
 [ 95. 153.  65. 108.  65.]
 [101. 

In [ ]:
L = evaluation_classif_L(pca_conf_mat)
N = evaluation_classif_N(pca_conf_mat)
R = evaluation_classif_R(pca_conf_mat)
S = evaluation_classif_S(pca_conf_mat)
T = evaluation_classif_T(pca_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST PCA JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost PCA JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost PCA JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost PCA JE ', prosecna_osetljivost)

# PROSECNA TACNOST PCA JE  0.7632982557301426
# PROSECNA specificnost PCA JE  0.8520306018746011
# PROSECNA preciznost PCA JE  0.40445529838967886
# PROSECNA osetljivost PCA JE  0.4080089662972097

PROSECNA TACNOST PCA JE  0.7632982557301426
PROSECNA specificnost PCA JE  0.8520306018746011
PROSECNA preciznost PCA JE  0.40445529838967886
PROSECNA osetljivost PCA JE  0.4080089662972097


In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=4
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
s = StandardScaler()
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=4)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 4, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 4, k= 35  i m= chebyshev weigth je: uniform  tacnost je:  0.7274047598255091  a mat. konf. je:
# [[ 930.  110.  165.  116.   25.]
#  [  89. 1041.   80.  104.  102.]
#  [ 134.   96.  952.  149.   15.]
#  [ 104.  154.  104.  940.  113.]
#  [  13.  120.   11.   87. 1183.]]

za parametre  n_components= 4, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.6439425128185935  a mat. konf. je:
[[ 835.  118.  206.  155.   32.]
 [ 141.  873.  101.  157.  144.]
 [ 194.  107.  861.  164.   20.]
 [ 158.  151.  162.  807.  137.]
 [  29.  139.   20.  135. 1091.]]
za parametre  n_components= 4, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.6439425128185935  a mat. konf. je:
[[ 835.  118.  206.  155.   32.]
 [ 141.  873.  101.  157.  144.]
 [ 194.  107.  861.  164.   20.]
 [ 158.  151.  162.  807.  137.]
 [  29.  139.   20.  135. 1091.]]
za parametre  n_components= 4, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6404818044587497  a mat. konf. je:
[[ 831.  126.  200.  159.   30.]
 [ 139.  865.  114.  152.  146.]
 [ 190.  114.  858.  163.   21.]
 [ 155.  154.  174.  799.  133.]
 [  31.  137.   16.  140. 1090.]]
za parametre  n_components= 4, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6404818044587497  a mat. konf. je:
[[ 831.  126

In [ ]:
#ODABIR OPTIMALNIH PARAMETARA ZA KNN, LDA N_KOMP=3
labels_y = ['L', 'N', 'R', 'S', 'T']
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
acc = []
for k in [1,5,10,15,20,30,35]:
    for m in ['euclidean', 'manhattan','chebyshev']:
        for l in ['uniform','distance']:
            indexes = kf.split(X_obuka, y_obuka)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
            for train_index, test_index in indexes:
                    X_std1 = s.fit_transform(X_obuka.iloc[train_index,:])
                    X_std_test = s.transform(X_obuka.iloc[test_index,:])
                    lda = LinearDiscriminantAnalysis(n_components=3)
                    lda.fit(X_std1,y_obuka.iloc[train_index])
                    X_train_r = lda.transform(X_std1)
                    X_test_r=lda.transform(X_std_test)
                    classifier = KNeighborsClassifier(n_neighbors=k, metric=m,weights=l)
                    classifier.fit(X_train_r, y_obuka.iloc[train_index])
                    y_pred = classifier.predict(X_test_r)
                    acc_tmp.append(accuracy_score(y_obuka.iloc[test_index], y_pred))
                    fin_conf_mat += confusion_matrix(y_obuka.iloc[test_index], y_pred, labels=labels_y)
            print('za parametre  n_components= 3, k=', k, ' i m=', m, 'weigth je:',l,' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

# za parametre  n_components= 3, k= 35  i m= manhattan weigth je: uniform  tacnost je:  0.6974223503041946  a mat. konf. je:
# [[ 905.  122.  154.  144.   21.]
#  [  96.  998.   99.   97.  126.]
#  [ 122.  127.  893.  191.   13.]
#  [ 130.  133.  140.  890.  122.]
#  [  12.  139.    0.  111. 1152.]]

za parametre  n_components= 3, k= 1  i m= euclidean weigth je: uniform  tacnost je:  0.6120810825421777  a mat. konf. je:
[[ 823.  135.  173.  192.   23.]
 [ 133.  843.  148.  113.  179.]
 [ 183.  156.  790.  201.   16.]
 [ 175.  120.  226.  737.  157.]
 [  29.  174.   18.  140. 1053.]]
za parametre  n_components= 3, k= 1  i m= euclidean weigth je: distance  tacnost je:  0.6120810825421777  a mat. konf. je:
[[ 823.  135.  173.  192.   23.]
 [ 133.  843.  148.  113.  179.]
 [ 183.  156.  790.  201.   16.]
 [ 175.  120.  226.  737.  157.]
 [  29.  174.   18.  140. 1053.]]
za parametre  n_components= 3, k= 1  i m= manhattan weigth je: uniform  tacnost je:  0.6146780692890204  a mat. konf. je:
[[ 828.  132.  176.  187.   23.]
 [ 130.  847.  160.  111.  168.]
 [ 189.  145.  799.  193.   20.]
 [ 184.  124.  219.  744.  144.]
 [  33.  175.   17.  143. 1046.]]
za parametre  n_components= 3, k= 1  i m= manhattan weigth je: distance  tacnost je:  0.6146780692890204  a mat. konf. je:
[[ 828.  132

In [ ]:
baze = [g0001,g0002,g0003,g0005,g1003,g1004,g1005,g1007,g1008,g1009,g1011,g1012,g1014,g1015,g1016,g1023,g1027,g1036,g1045,g1051,g1053,g1057,g1060]
labels_y = ['L', 'N', 'R', 'S', 'T']
acc = []
LDA_conf_mat = np.zeros((len(np.unique(y_obuka)),len(np.unique(y_obuka))))
for i in range(0,len(baze)):
  izbaci = baze[i].index
  obuka = bez_imena.drop(izbaci, axis = 0)
  test = baze[i]

  acc_tmp = []
  X_obuka29= obuka.iloc[:, :-1]
  y_obuka29 = obuka.iloc[:, -1]
  s = StandardScaler()
  XLDA_obuka29_std = s.fit_transform(X_obuka29)

  X_test1= test.iloc[:, :-1]
  y_test1 = test.iloc[:, -1]
  XLDA_test1_std = s.transform(X_test1)

  lda = LinearDiscriminantAnalysis(n_components=4)
  lda.fit(XLDA_obuka29_std, y_obuka29)
  X_train_29_lda = lda.transform(XLDA_obuka29_std)
  X_test_29_lda = lda.transform(XLDA_test1_std)

  classifier_kon = KNeighborsClassifier(n_neighbors=35, metric='chebyshev',weights='uniform')
  classifier_kon.fit(X_train_29_lda, y_obuka29)

  # testiranje
  y_pred_kon = classifier_kon.predict(X_test_29_lda)
  conf_mat_knn1 = confusion_matrix(y_test1, y_pred_kon, labels=labels_y)
  #print(conf_mat_knnSZ)

  #acc_tmp.append(accuracy_score(y_test1, y_pred_kon))
  LDA_conf_mat += confusion_matrix(y_test1, y_pred_kon, labels=labels_y)

  print(LDA_conf_mat)

#   [[569. 198. 243. 242.  94.]
#  [214. 515. 200. 226. 261.]
#  [226. 209. 642. 184.  85.]
#  [212. 247. 200. 534. 222.]
#  [ 46. 196.  65. 131. 976.]]

[[13.  4. 40.  0.  0.]
 [ 0.  9. 50.  1.  0.]
 [ 0.  0. 57.  0.  0.]
 [ 0.  0. 37. 23.  0.]
 [ 1. 10. 42.  7.  0.]]
[[26. 39. 44.  1.  4.]
 [ 1. 59. 52.  5.  3.]
 [ 3. 45. 60.  4.  2.]
 [ 0. 30. 37. 42. 11.]
 [ 1. 15. 42. 18. 44.]]
[[ 35.  41.  83.   8.   4.]
 [  4. 108.  52.  13.   3.]
 [ 12.  57.  91.   9.   2.]
 [  3.  46.  65.  54.  12.]
 [  1.  23.  42.  25.  89.]]
[[ 35.  51.  87.  51.   4.]
 [  5. 113.  56.  63.   3.]
 [ 18.  57. 115.  36.   2.]
 [  6.  46.  65. 111.  12.]
 [  1.  31.  42.  26. 140.]]
[[ 92.  51.  87.  51.   4.]
 [ 28. 138.  60.  64.  10.]
 [ 59.  61. 126.  37.   2.]
 [ 25.  53.  75. 125.  22.]
 [  1.  31.  42.  26. 200.]]
[[122.  63.  97.  53.   9.]
 [ 29. 165.  65.  64.  39.]
 [ 61.  93. 144.  37.   9.]
 [ 29.  76.  76. 126.  55.]
 [  1.  39.  42.  26. 254.]]
[[165.  76.  97.  56.   9.]
 [ 34. 215.  65.  65.  45.]
 [ 93.  99. 165.  37.   9.]
 [ 51.  88.  76. 148.  61.]
 [  2.  52.  42.  26. 302.]]
[[207.  84. 103.  59.   9.]
 [ 37. 254.  65.  83.  47.]
 [106. 

In [ ]:
L = evaluation_classif_L(LDA_conf_mat)
N = evaluation_classif_N(LDA_conf_mat)
R = evaluation_classif_R(LDA_conf_mat)
S = evaluation_classif_S(LDA_conf_mat)
T = evaluation_classif_T(LDA_conf_mat)

prosecna_tacnost = (L[0]+N[0]+R[0]+S[0]+T[0])/5
print('PROSECNA TACNOST LDA JE ', prosecna_tacnost)

prosecna_specificnost = (L[3]+N[3]+R[3]+S[3]+T[3])/5
print('PROSECNA specificnost LDA JE ', prosecna_specificnost)

prosecna_preciznost = (L[1]+N[1]+R[1]+S[1]+T[1])/5
print('PROSECNA preciznost LDA JE ', prosecna_preciznost)

prosecna_osetljivost = (L[2]+N[2]+R[2]+S[2]+T[2])/5
print('PROSECNA osetljivost LDA JE ', prosecna_osetljivost)

# PROSECNA TACNOST LDA JE  0.7865936283696122
# PROSECNA specificnost LDA JE  0.8665815907350558
# PROSECNA preciznost LDA JE  0.4606505686401482
# PROSECNA osetljivost LDA JE  0.46620579995576683

PROSECNA TACNOST LDA JE  0.7865936283696122
PROSECNA specificnost LDA JE  0.8665815907350558
PROSECNA preciznost LDA JE  0.4606505686401482
PROSECNA osetljivost LDA JE  0.46620579995576683
